# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dora_client
from dora_client.models.withdraw_request import WithdrawRequest  # noqa: E501
from dora_client.rest import ApiException


class TestWithdrawRequest(unittest.TestCase):
    """WithdrawRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWithdrawRequest(self):
        """Test WithdrawRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dora_client.models.withdraw_request.WithdrawRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
