# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dora_client
from dora_client.models.fund_user import FundUser  # noqa: E501
from dora_client.rest import ApiException


class TestFundUser(unittest.TestCase):
    """FundUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFundUser(self):
        """Test FundUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dora_client.models.fund_user.FundUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
