# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.get_asset_by_id_response_envelope import GetAssetByIDResponseEnvelope

class TestGetAssetByIDResponseEnvelope(unittest.TestCase):
    """GetAssetByIDResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAssetByIDResponseEnvelope:
        """Test GetAssetByIDResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAssetByIDResponseEnvelope`
        """
        model = GetAssetByIDResponseEnvelope()
        if include_optional:
            return GetAssetByIDResponseEnvelope(
                data = dora_client.models.asset.Asset(
                    id = '', 
                    collateral_weight = 0, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    decimals = 0, 
                    fractionalized_units = 1, 
                    description = '', 
                    liquidation_weight = 0, 
                    max_supply = 0, 
                    max_utilization = 0, 
                    minimum_rate = 0, 
                    kink_rate = 0, 
                    maximum_rate = 0, 
                    kink_utilization = 0, 
                    name = '', 
                    symbol = '', 
                    kind = 'BOND', 
                    yield = 0, 
                    can_add_liquidity = True, 
                    can_direct_borrow = True, 
                    can_onboard = True, 
                    can_trade = True, 
                    can_virtual_borrow = True, 
                    max_leverage = 1, 
                    leverage_interest_rate = 1.337, 
                    bond = null, ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return GetAssetByIDResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testGetAssetByIDResponseEnvelope(self):
        """Test GetAssetByIDResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
