# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.cash_reserve_response import CashReserveResponse

class TestCashReserveResponse(unittest.TestCase):
    """CashReserveResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CashReserveResponse:
        """Test CashReserveResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CashReserveResponse`
        """
        model = CashReserveResponse()
        if include_optional:
            return CashReserveResponse(
                enforced = True,
                available_usd = '',
                committed_usd = '',
                required_usd = '',
                satisfied = True,
                breakdown = dora_client.models.cash_reserve_breakdown.CashReserveBreakdown(
                    completed_pac = '', 
                    outstanding_lai = '', 
                    estimated_fees = '', 
                    borrowed_portion = '', 
                    floor = '', 
                    total = '', )
            )
        else:
            return CashReserveResponse(
                enforced = True,
                available_usd = '',
                committed_usd = '',
                required_usd = '',
                satisfied = True,
                breakdown = dora_client.models.cash_reserve_breakdown.CashReserveBreakdown(
                    completed_pac = '', 
                    outstanding_lai = '', 
                    estimated_fees = '', 
                    borrowed_portion = '', 
                    floor = '', 
                    total = '', ),
        )
        """

    def testCashReserveResponse(self):
        """Test CashReserveResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
