# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.trading_challenge_registration_request import TradingChallengeRegistrationRequest

class TestTradingChallengeRegistrationRequest(unittest.TestCase):
    """TradingChallengeRegistrationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradingChallengeRegistrationRequest:
        """Test TradingChallengeRegistrationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradingChallengeRegistrationRequest`
        """
        model = TradingChallengeRegistrationRequest()
        if include_optional:
            return TradingChallengeRegistrationRequest(
                id = '',
                trading_challenge_id = '',
                trading_challenge_name = '',
                trading_challenge_type = 'TOURNAMENT',
                trading_challenge_status = 'PENDING',
                user_id = '',
                user_email = '',
                user_name = '',
                tenant_id = '',
                status = 'PENDING',
                reviewed_by = '',
                reviewed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                review_reason = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TradingChallengeRegistrationRequest(
                id = '',
                trading_challenge_id = '',
                user_id = '',
                tenant_id = '',
                status = 'PENDING',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTradingChallengeRegistrationRequest(self):
        """Test TradingChallengeRegistrationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
