# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.united_position import UnitedPosition

class TestUnitedPosition(unittest.TestCase):
    """UnitedPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitedPosition:
        """Test UnitedPosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitedPosition`
        """
        model = UnitedPosition()
        if include_optional:
            return UnitedPosition(
                global_position_id = '',
                transaction_ids = [
                    ''
                    ]
            )
        else:
            return UnitedPosition(
                global_position_id = '',
                transaction_ids = [
                    ''
                    ],
        )
        """

    def testUnitedPosition(self):
        """Test UnitedPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
