# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.module_balance import ModuleBalance

class TestModuleBalance(unittest.TestCase):
    """ModuleBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModuleBalance:
        """Test ModuleBalance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModuleBalance`
        """
        model = ModuleBalance()
        if include_optional:
            return ModuleBalance(
                asset_id = '',
                seq = 1,
                available = '',
                supplied = '',
                virtual = '',
                borrowed = ''
            )
        else:
            return ModuleBalance(
                asset_id = '',
                seq = 1,
                available = '',
                supplied = '',
                virtual = '',
                borrowed = '',
        )
        """

    def testModuleBalance(self):
        """Test ModuleBalance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
