# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.terminate_trading_challenge_response_envelope import TerminateTradingChallengeResponseEnvelope

class TestTerminateTradingChallengeResponseEnvelope(unittest.TestCase):
    """TerminateTradingChallengeResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TerminateTradingChallengeResponseEnvelope:
        """Test TerminateTradingChallengeResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TerminateTradingChallengeResponseEnvelope`
        """
        model = TerminateTradingChallengeResponseEnvelope()
        if include_optional:
            return TerminateTradingChallengeResponseEnvelope(
                data = dora_client.models.terminate_trading_challenge_response.TerminateTradingChallengeResponse(
                    trading_challenge_id = '', 
                    user_id = '', 
                    status = 'TERMINATED', ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return TerminateTradingChallengeResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testTerminateTradingChallengeResponseEnvelope(self):
        """Test TerminateTradingChallengeResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
