# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.promo_link_list_response_all_of_data import PromoLinkListResponseAllOfData

class TestPromoLinkListResponseAllOfData(unittest.TestCase):
    """PromoLinkListResponseAllOfData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromoLinkListResponseAllOfData:
        """Test PromoLinkListResponseAllOfData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromoLinkListResponseAllOfData`
        """
        model = PromoLinkListResponseAllOfData()
        if include_optional:
            return PromoLinkListResponseAllOfData(
                links = [
                    dora_client.models.promo_link_admin.PromoLinkAdmin(
                        id = '', 
                        token_prefix = '', 
                        url = '', 
                        status = 'ISSUED', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        claimed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        claimed_email = '', 
                        user_id = '', )
                    ],
                next_cursor = ''
            )
        else:
            return PromoLinkListResponseAllOfData(
                links = [
                    dora_client.models.promo_link_admin.PromoLinkAdmin(
                        id = '', 
                        token_prefix = '', 
                        url = '', 
                        status = 'ISSUED', 
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        claimed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        claimed_email = '', 
                        user_id = '', )
                    ],
        )
        """

    def testPromoLinkListResponseAllOfData(self):
        """Test PromoLinkListResponseAllOfData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
