# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.stream_user_coupon_payments_entry import StreamUserCouponPaymentsEntry

class TestStreamUserCouponPaymentsEntry(unittest.TestCase):
    """StreamUserCouponPaymentsEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamUserCouponPaymentsEntry:
        """Test StreamUserCouponPaymentsEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamUserCouponPaymentsEntry`
        """
        model = StreamUserCouponPaymentsEntry()
        if include_optional:
            return StreamUserCouponPaymentsEntry(
                val = dora_client.models.user_coupon_payment.UserCouponPayment(
                    user_id = '', 
                    position_id = '', 
                    asset_id = '', 
                    coupon_payment_id = '', 
                    seq = 0, 
                    pending = '', 
                    completed = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return StreamUserCouponPaymentsEntry(
                val = dora_client.models.user_coupon_payment.UserCouponPayment(
                    user_id = '', 
                    position_id = '', 
                    asset_id = '', 
                    coupon_payment_id = '', 
                    seq = 0, 
                    pending = '', 
                    completed = '', 
                    started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testStreamUserCouponPaymentsEntry(self):
        """Test StreamUserCouponPaymentsEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
