# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.asset_kind import AssetKind

class TestAssetKind(unittest.TestCase):
    """AssetKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetKind(self):
        """Test AssetKind"""
        # inst = AssetKind()

if __name__ == '__main__':
    unittest.main()
