# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.validate_submit_order_request import ValidateSubmitOrderRequest

class TestValidateSubmitOrderRequest(unittest.TestCase):
    """ValidateSubmitOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateSubmitOrderRequest:
        """Test ValidateSubmitOrderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateSubmitOrderRequest`
        """
        model = ValidateSubmitOrderRequest()
        if include_optional:
            return ValidateSubmitOrderRequest(
                quantity = '',
                tick = '',
                kind = 'LIMIT',
                side = 'BUY',
                price = '',
                good_till_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                inverse_leverage = '',
                user_balance = '',
                base_asset_id = '',
                quote_asset_id = '',
                client_order_id = '',
                position_assets = [
                    dora_client.models.position_asset.PositionAsset(
                        asset_id = '', 
                        kind = 'BOND', 
                        borrowed = '', 
                        impending_borrows = '', 
                        available = '', 
                        locked = '', )
                    ],
                assets_config = [
                    dora_client.models.asset_config.AssetConfig(
                        asset_id = '', 
                        price = '', )
                    ],
                stop_loss_price = '',
                take_profit_price = ''
            )
        else:
            return ValidateSubmitOrderRequest(
                quantity = '',
                tick = '',
                kind = 'LIMIT',
                price = '',
                inverse_leverage = '',
                user_balance = '',
        )
        """

    def testValidateSubmitOrderRequest(self):
        """Test ValidateSubmitOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
