# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.promo_link_batch_list_response_all_of_data import PromoLinkBatchListResponseAllOfData

class TestPromoLinkBatchListResponseAllOfData(unittest.TestCase):
    """PromoLinkBatchListResponseAllOfData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromoLinkBatchListResponseAllOfData:
        """Test PromoLinkBatchListResponseAllOfData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromoLinkBatchListResponseAllOfData`
        """
        model = PromoLinkBatchListResponseAllOfData()
        if include_optional:
            return PromoLinkBatchListResponseAllOfData(
                batches = [
                    dora_client.models.promo_link_batch_summary.PromoLinkBatchSummary(
                        id = '', 
                        source_type = 'KOL', 
                        source_id = '', 
                        source_name = '', 
                        allocation = 56, 
                        issued = 56, 
                        claimed = 56, 
                        revoked = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PromoLinkBatchListResponseAllOfData(
                batches = [
                    dora_client.models.promo_link_batch_summary.PromoLinkBatchSummary(
                        id = '', 
                        source_type = 'KOL', 
                        source_id = '', 
                        source_name = '', 
                        allocation = 56, 
                        issued = 56, 
                        claimed = 56, 
                        revoked = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testPromoLinkBatchListResponseAllOfData(self):
        """Test PromoLinkBatchListResponseAllOfData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
