# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.permit_domain import PermitDomain

class TestPermitDomain(unittest.TestCase):
    """PermitDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermitDomain:
        """Test PermitDomain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermitDomain`
        """
        model = PermitDomain()
        if include_optional:
            return PermitDomain(
                name = '',
                version = '',
                chain_id = 56,
                verifying_contract = ''
            )
        else:
            return PermitDomain(
                name = '',
                version = '',
                chain_id = 56,
                verifying_contract = '',
        )
        """

    def testPermitDomain(self):
        """Test PermitDomain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
