# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dora_client
from dora_client.models.united_position import UnitedPosition  # noqa: E501
from dora_client.rest import ApiException


class TestUnitedPosition(unittest.TestCase):
    """UnitedPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitedPosition(self):
        """Test UnitedPosition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dora_client.models.united_position.UnitedPosition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
