# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.live_orderbook import LiveOrderbook

class TestLiveOrderbook(unittest.TestCase):
    """LiveOrderbook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveOrderbook:
        """Test LiveOrderbook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveOrderbook`
        """
        model = LiveOrderbook()
        if include_optional:
            return LiveOrderbook(
                bids = [
                    dora_client.models.price_level.PriceLevel(
                        price = '', 
                        quantity = '', )
                    ],
                asks = [
                    dora_client.models.price_level.PriceLevel(
                        price = '', 
                        quantity = '', )
                    ]
            )
        else:
            return LiveOrderbook(
                bids = [
                    dora_client.models.price_level.PriceLevel(
                        price = '', 
                        quantity = '', )
                    ],
                asks = [
                    dora_client.models.price_level.PriceLevel(
                        price = '', 
                        quantity = '', )
                    ],
        )
        """

    def testLiveOrderbook(self):
        """Test LiveOrderbook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
