# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.deposit_instructions_response_envelope import DepositInstructionsResponseEnvelope

class TestDepositInstructionsResponseEnvelope(unittest.TestCase):
    """DepositInstructionsResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepositInstructionsResponseEnvelope:
        """Test DepositInstructionsResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepositInstructionsResponseEnvelope`
        """
        model = DepositInstructionsResponseEnvelope()
        if include_optional:
            return DepositInstructionsResponseEnvelope(
                data = dora_client.models.deposit_instructions_response.DepositInstructionsResponse(
                    user_id = '', 
                    owner_address = '', 
                    quantity = '', 
                    chains = [
                        dora_client.models.deposit_instruction_for_chain.DepositInstructionForChain(
                            network_name = '', 
                            chain_id = '', 
                            contract_address = '', 
                            usdc_address = '', 
                            approval = dora_client.models.permit_typed_data.PermitTypedData(
                                types = {
                                    'key' : [
                                        dora_client.models.typed_data_field.TypedDataField(
                                            name = '', 
                                            type = '', )
                                        ]
                                    }, 
                                primary_type = '', 
                                domain = dora_client.models.permit_domain.PermitDomain(
                                    name = '', 
                                    version = '', 
                                    chain_id = 56, 
                                    verifying_contract = '', ), 
                                message = dora_client.models.permit_message.PermitMessage(
                                    owner = '', 
                                    spender = '', 
                                    value = '', 
                                    nonce = '', 
                                    deadline = '', ), ), 
                            deposit = dora_client.models.deposit_call.DepositCall(
                                to = '', 
                                chain_id = 56, 
                                value = '', 
                                function_signature = '', 
                                selector = '', 
                                args = dora_client.models.deposit_args.DepositArgs(
                                    quantity = '', 
                                    user_id = '', 
                                    client_reference_id = '', 
                                    deadline = '', ), ), )
                        ], ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return DepositInstructionsResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testDepositInstructionsResponseEnvelope(self):
        """Test DepositInstructionsResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
