# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.close_position_response_envelope import ClosePositionResponseEnvelope

class TestClosePositionResponseEnvelope(unittest.TestCase):
    """ClosePositionResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClosePositionResponseEnvelope:
        """Test ClosePositionResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClosePositionResponseEnvelope`
        """
        model = ClosePositionResponseEnvelope()
        if include_optional:
            return ClosePositionResponseEnvelope(
                data = dora_client.models.order_id.OrderId(
                    order_id = '', ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return ClosePositionResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testClosePositionResponseEnvelope(self):
        """Test ClosePositionResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
