# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.affiliate_program_list_envelope import AffiliateProgramListEnvelope

class TestAffiliateProgramListEnvelope(unittest.TestCase):
    """AffiliateProgramListEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliateProgramListEnvelope:
        """Test AffiliateProgramListEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliateProgramListEnvelope`
        """
        model = AffiliateProgramListEnvelope()
        if include_optional:
            return AffiliateProgramListEnvelope(
                data = [
                    dora_client.models.affiliate_program.AffiliateProgram(
                        id = '', 
                        tenant_id = '0', 
                        name = '0', 
                        description = '', 
                        is_active = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return AffiliateProgramListEnvelope(
                data = [
                    dora_client.models.affiliate_program.AffiliateProgram(
                        id = '', 
                        tenant_id = '0', 
                        name = '0', 
                        description = '', 
                        is_active = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testAffiliateProgramListEnvelope(self):
        """Test AffiliateProgramListEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
