# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.register_affiliate_referrer_request import RegisterAffiliateReferrerRequest

class TestRegisterAffiliateReferrerRequest(unittest.TestCase):
    """RegisterAffiliateReferrerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterAffiliateReferrerRequest:
        """Test RegisterAffiliateReferrerRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterAffiliateReferrerRequest`
        """
        model = RegisterAffiliateReferrerRequest()
        if include_optional:
            return RegisterAffiliateReferrerRequest(
                user_id = '',
                referral_code = 'TEAM-42'
            )
        else:
            return RegisterAffiliateReferrerRequest(
                user_id = '',
        )
        """

    def testRegisterAffiliateReferrerRequest(self):
        """Test RegisterAffiliateReferrerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
