# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.transaction_kind import TransactionKind

class TestTransactionKind(unittest.TestCase):
    """TransactionKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionKind(self):
        """Test TransactionKind"""
        # inst = TransactionKind()

if __name__ == '__main__':
    unittest.main()
