# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dora_client
from dora_client.models.list_bot_strategies_trades import ListBotStrategiesTrades  # noqa: E501
from dora_client.rest import ApiException


class TestListBotStrategiesTrades(unittest.TestCase):
    """ListBotStrategiesTrades unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListBotStrategiesTrades(self):
        """Test ListBotStrategiesTrades"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dora_client.models.list_bot_strategies_trades.ListBotStrategiesTrades()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
