# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.withdrawal_initiation import WithdrawalInitiation

class TestWithdrawalInitiation(unittest.TestCase):
    """WithdrawalInitiation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithdrawalInitiation:
        """Test WithdrawalInitiation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WithdrawalInitiation`
        """
        model = WithdrawalInitiation()
        if include_optional:
            return WithdrawalInitiation(
                withdrawal_id = '',
                user_id = '',
                position_id = '',
                asset_id = '',
                quantity = '',
                status = 'PENDING',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                reason = ''
            )
        else:
            return WithdrawalInitiation(
                withdrawal_id = '',
                user_id = '',
                position_id = '',
                asset_id = '',
                quantity = '',
                status = 'PENDING',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                reason = '',
        )
        """

    def testWithdrawalInitiation(self):
        """Test WithdrawalInitiation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
