# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.stream_user_coupon_payments_response import StreamUserCouponPaymentsResponse

class TestStreamUserCouponPaymentsResponse(unittest.TestCase):
    """StreamUserCouponPaymentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamUserCouponPaymentsResponse:
        """Test StreamUserCouponPaymentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamUserCouponPaymentsResponse`
        """
        model = StreamUserCouponPaymentsResponse()
        if include_optional:
            return StreamUserCouponPaymentsResponse(
                entries = [
                    dora_client.models.stream_user_coupon_payments_entry.StreamUserCouponPaymentsEntry()
                    ],
                summary_by_asset = [
                    dora_client.models.user_coupon_payment_asset_summary.UserCouponPaymentAssetSummary(
                        asset_id = '', 
                        pending = '', 
                        completed = '', )
                    ]
            )
        else:
            return StreamUserCouponPaymentsResponse(
        )
        """

    def testStreamUserCouponPaymentsResponse(self):
        """Test StreamUserCouponPaymentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
