# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.order_book_status import OrderBookStatus

class TestOrderBookStatus(unittest.TestCase):
    """OrderBookStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderBookStatus(self):
        """Test OrderBookStatus"""
        # inst = OrderBookStatus()

if __name__ == '__main__':
    unittest.main()
