# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.trading_challenge_daily_snapshots_response_envelope import TradingChallengeDailySnapshotsResponseEnvelope

class TestTradingChallengeDailySnapshotsResponseEnvelope(unittest.TestCase):
    """TradingChallengeDailySnapshotsResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TradingChallengeDailySnapshotsResponseEnvelope:
        """Test TradingChallengeDailySnapshotsResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradingChallengeDailySnapshotsResponseEnvelope`
        """
        model = TradingChallengeDailySnapshotsResponseEnvelope()
        if include_optional:
            return TradingChallengeDailySnapshotsResponseEnvelope(
                data = [
                    dora_client.models.trading_challenge_daily_snapshot.TradingChallengeDailySnapshot(
                        trading_challenge_id = '', 
                        user_id = '', 
                        user_name = '', 
                        trading_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        daily_volume = '', 
                        daily_pnl = '', 
                        daily_trades = 56, 
                        volume_compliant = True, 
                        eod_equity = '', 
                        active_day = True, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return TradingChallengeDailySnapshotsResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testTradingChallengeDailySnapshotsResponseEnvelope(self):
        """Test TradingChallengeDailySnapshotsResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
