# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.deposit_args import DepositArgs

class TestDepositArgs(unittest.TestCase):
    """DepositArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepositArgs:
        """Test DepositArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepositArgs`
        """
        model = DepositArgs()
        if include_optional:
            return DepositArgs(
                quantity = '',
                user_id = '',
                client_reference_id = '',
                deadline = ''
            )
        else:
            return DepositArgs(
                quantity = '',
                user_id = '',
                client_reference_id = '',
                deadline = '',
        )
        """

    def testDepositArgs(self):
        """Test DepositArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
