# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.asset_price_response_envelope import AssetPriceResponseEnvelope

class TestAssetPriceResponseEnvelope(unittest.TestCase):
    """AssetPriceResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetPriceResponseEnvelope:
        """Test AssetPriceResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetPriceResponseEnvelope`
        """
        model = AssetPriceResponseEnvelope()
        if include_optional:
            return AssetPriceResponseEnvelope(
                data = dora_client.models.asset_price.AssetPrice(
                    asset_id = '', 
                    price = '', 
                    ytm = '', 
                    time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return AssetPriceResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testAssetPriceResponseEnvelope(self):
        """Test AssetPriceResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
