# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dora_client
from dora_client.models.pl_asset import PLAsset  # noqa: E501
from dora_client.rest import ApiException


class TestPLAsset(unittest.TestCase):
    """PLAsset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPLAsset(self):
        """Test PLAsset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dora_client.models.pl_asset.PLAsset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
