# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.permit_typed_data import PermitTypedData

class TestPermitTypedData(unittest.TestCase):
    """PermitTypedData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermitTypedData:
        """Test PermitTypedData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermitTypedData`
        """
        model = PermitTypedData()
        if include_optional:
            return PermitTypedData(
                types = {
                    'key' : [
                        dora_client.models.typed_data_field.TypedDataField(
                            name = '', 
                            type = '', )
                        ]
                    },
                primary_type = '',
                domain = dora_client.models.permit_domain.PermitDomain(
                    name = '', 
                    version = '', 
                    chain_id = 56, 
                    verifying_contract = '', ),
                message = dora_client.models.permit_message.PermitMessage(
                    owner = '', 
                    spender = '', 
                    value = '', 
                    nonce = '', 
                    deadline = '', )
            )
        else:
            return PermitTypedData(
                types = {
                    'key' : [
                        dora_client.models.typed_data_field.TypedDataField(
                            name = '', 
                            type = '', )
                        ]
                    },
                primary_type = '',
                domain = dora_client.models.permit_domain.PermitDomain(
                    name = '', 
                    version = '', 
                    chain_id = 56, 
                    verifying_contract = '', ),
                message = dora_client.models.permit_message.PermitMessage(
                    owner = '', 
                    spender = '', 
                    value = '', 
                    nonce = '', 
                    deadline = '', ),
        )
        """

    def testPermitTypedData(self):
        """Test PermitTypedData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
