# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.claim_leverage_accrued_interest_request import ClaimLeverageAccruedInterestRequest

class TestClaimLeverageAccruedInterestRequest(unittest.TestCase):
    """ClaimLeverageAccruedInterestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClaimLeverageAccruedInterestRequest:
        """Test ClaimLeverageAccruedInterestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClaimLeverageAccruedInterestRequest`
        """
        model = ClaimLeverageAccruedInterestRequest()
        if include_optional:
            return ClaimLeverageAccruedInterestRequest(
                position_id = '',
                asset_id = '',
                quantity = ''
            )
        else:
            return ClaimLeverageAccruedInterestRequest(
                position_id = '',
                asset_id = '',
                quantity = '',
        )
        """

    def testClaimLeverageAccruedInterestRequest(self):
        """Test ClaimLeverageAccruedInterestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
