# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.stream_current_leverage_accrued_interest_response import StreamCurrentLeverageAccruedInterestResponse

class TestStreamCurrentLeverageAccruedInterestResponse(unittest.TestCase):
    """StreamCurrentLeverageAccruedInterestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamCurrentLeverageAccruedInterestResponse:
        """Test StreamCurrentLeverageAccruedInterestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamCurrentLeverageAccruedInterestResponse`
        """
        model = StreamCurrentLeverageAccruedInterestResponse()
        if include_optional:
            return StreamCurrentLeverageAccruedInterestResponse(
                current_leverage_accrued_interest = [
                    dora_client.models.current_leverage_accrued_interest.CurrentLeverageAccruedInterest(
                        user_id = '', 
                        asset_id = '', 
                        position_id = '', 
                        current_accrued_interest_usd = '', 
                        asset_name = '', 
                        asset_symbol = '', )
                    ]
            )
        else:
            return StreamCurrentLeverageAccruedInterestResponse(
        )
        """

    def testStreamCurrentLeverageAccruedInterestResponse(self):
        """Test StreamCurrentLeverageAccruedInterestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
