# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.deposit_response import DepositResponse

class TestDepositResponse(unittest.TestCase):
    """DepositResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepositResponse:
        """Test DepositResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepositResponse`
        """
        model = DepositResponse()
        if include_optional:
            return DepositResponse(
                network_chain_id = 56,
                network_name = '',
                chain_id = '',
                tx_hash = '',
                log_index = 56,
                block_number = 56,
                block_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                contract_address = '',
                depositor_address = '',
                user_id = '',
                quantity = '',
                client_reference_id = '',
                status = 'PENDING',
                transaction_id = '',
                observed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DepositResponse(
                network_chain_id = 56,
                network_name = '',
                chain_id = '',
                tx_hash = '',
                log_index = 56,
                block_number = 56,
                block_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                contract_address = '',
                depositor_address = '',
                user_id = '',
                quantity = '',
                status = 'PENDING',
                observed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testDepositResponse(self):
        """Test DepositResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
