# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.order_book_summary_response_envelope import OrderBookSummaryResponseEnvelope

class TestOrderBookSummaryResponseEnvelope(unittest.TestCase):
    """OrderBookSummaryResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderBookSummaryResponseEnvelope:
        """Test OrderBookSummaryResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderBookSummaryResponseEnvelope`
        """
        model = OrderBookSummaryResponseEnvelope()
        if include_optional:
            return OrderBookSummaryResponseEnvelope(
                data = dora_client.models.order_book_summary.OrderBookSummary(
                    order_book_id = '', 
                    mid_price = '', 
                    spread = '', 
                    best_bid = '', 
                    best_ask = '', ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return OrderBookSummaryResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testOrderBookSummaryResponseEnvelope(self):
        """Test OrderBookSummaryResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
