# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.tenant_guarantee_fund_history_response_envelope import TenantGuaranteeFundHistoryResponseEnvelope

class TestTenantGuaranteeFundHistoryResponseEnvelope(unittest.TestCase):
    """TenantGuaranteeFundHistoryResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantGuaranteeFundHistoryResponseEnvelope:
        """Test TenantGuaranteeFundHistoryResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantGuaranteeFundHistoryResponseEnvelope`
        """
        model = TenantGuaranteeFundHistoryResponseEnvelope()
        if include_optional:
            return TenantGuaranteeFundHistoryResponseEnvelope(
                data = dora_client.models.tenant_guarantee_fund_history.TenantGuaranteeFundHistory(
                    rows = [
                        dora_client.models.tenant_guarantee_fund_row.TenantGuaranteeFundRow(
                            id = '', 
                            tenant_id = '', 
                            seq = 56, 
                            available = '', 
                            tx_kind = 'DEPOSIT', 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    summary = dora_client.models.tenant_guarantee_fund_summary.TenantGuaranteeFundSummary(
                        totals_by_tx_kind = {
                            'key' : ''
                            }, ), ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return TenantGuaranteeFundHistoryResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testTenantGuaranteeFundHistoryResponseEnvelope(self):
        """Test TenantGuaranteeFundHistoryResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
