# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.create_api_key_response_envelope import CreateAPIKeyResponseEnvelope

class TestCreateAPIKeyResponseEnvelope(unittest.TestCase):
    """CreateAPIKeyResponseEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAPIKeyResponseEnvelope:
        """Test CreateAPIKeyResponseEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAPIKeyResponseEnvelope`
        """
        model = CreateAPIKeyResponseEnvelope()
        if include_optional:
            return CreateAPIKeyResponseEnvelope(
                data = dora_client.models.create_api_key_data.CreateAPIKeyData(
                    key_id = '', 
                    api_key = '', 
                    label = '', ),
                error = '',
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', )
            )
        else:
            return CreateAPIKeyResponseEnvelope(
                metadata = dora_client.models.metadata.Metadata(
                    status_code = 56, 
                    trace_id = '', 
                    request_id = '', ),
        )
        """

    def testCreateAPIKeyResponseEnvelope(self):
        """Test CreateAPIKeyResponseEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
