# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.fee_quote_response import FeeQuoteResponse

class TestFeeQuoteResponse(unittest.TestCase):
    """FeeQuoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeeQuoteResponse:
        """Test FeeQuoteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeeQuoteResponse`
        """
        model = FeeQuoteResponse()
        if include_optional:
            return FeeQuoteResponse(
                withdrawal_id = '',
                to = '',
                quantity = '',
                fee = '',
                fee_base_units = '',
                chain_id = '',
                quote_token = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FeeQuoteResponse(
                withdrawal_id = '',
                to = '',
                quantity = '',
                fee = '',
                fee_base_units = '',
                chain_id = '',
                quote_token = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testFeeQuoteResponse(self):
        """Test FeeQuoteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
