# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.isolated_position import IsolatedPosition

class TestIsolatedPosition(unittest.TestCase):
    """IsolatedPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsolatedPosition:
        """Test IsolatedPosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsolatedPosition`
        """
        model = IsolatedPosition()
        if include_optional:
            return IsolatedPosition(
                global_position_id = '',
                isolated_position_id = '',
                transaction_id = ''
            )
        else:
            return IsolatedPosition(
                global_position_id = '',
                isolated_position_id = '',
                transaction_id = '',
        )
        """

    def testIsolatedPosition(self):
        """Test IsolatedPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
