# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.update_trading_challenge_request import UpdateTradingChallengeRequest

class TestUpdateTradingChallengeRequest(unittest.TestCase):
    """UpdateTradingChallengeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTradingChallengeRequest:
        """Test UpdateTradingChallengeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTradingChallengeRequest`
        """
        model = UpdateTradingChallengeRequest()
        if include_optional:
            return UpdateTradingChallengeRequest(
                name = dora_client.models.update_field_string.UpdateFieldString(
                    update = True, 
                    value = '', ),
                type = dora_client.models.update_field_string.UpdateFieldString(
                    update = True, 
                    value = '', ),
                max_users = dora_client.models.update_field_integer.UpdateFieldInteger(
                    update = True, 
                    value = 56, ),
                start = dora_client.models.update_field_date_time.UpdateFieldDateTime(
                    update = True, 
                    value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                end = dora_client.models.update_field_date_time.UpdateFieldDateTime(
                    update = True, 
                    value = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                initial_user_balance = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                gold_prize_quantity = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                silver_prize_quantity = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                bronze_prize_quantity = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                pnl_condition = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                total_volume_condition = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                avg_daily_volume_condition = dora_client.models.update_field_decimal.UpdateFieldDecimal(
                    update = True, 
                    value = '', ),
                minimum_equity_percentage_condition = dora_client.models.update_field_integer.UpdateFieldInteger(
                    update = True, 
                    value = 56, )
            )
        else:
            return UpdateTradingChallengeRequest(
        )
        """

    def testUpdateTradingChallengeRequest(self):
        """Test UpdateTradingChallengeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
