# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dora_client
from dora_client.models.settle_leverage_accrued_interest_request import SettleLeverageAccruedInterestRequest  # noqa: E501
from dora_client.rest import ApiException


class TestSettleLeverageAccruedInterestRequest(unittest.TestCase):
    """SettleLeverageAccruedInterestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettleLeverageAccruedInterestRequest(self):
        """Test SettleLeverageAccruedInterestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dora_client.models.settle_leverage_accrued_interest_request.SettleLeverageAccruedInterestRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
