# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dora_client.models.stream_order_book_balances_response import StreamOrderBookBalancesResponse

class TestStreamOrderBookBalancesResponse(unittest.TestCase):
    """StreamOrderBookBalancesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamOrderBookBalancesResponse:
        """Test StreamOrderBookBalancesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamOrderBookBalancesResponse`
        """
        model = StreamOrderBookBalancesResponse()
        if include_optional:
            return StreamOrderBookBalancesResponse(
            )
        else:
            return StreamOrderBookBalancesResponse(
        )
        """

    def testStreamOrderBookBalancesResponse(self):
        """Test StreamOrderBookBalancesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
