# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from dora_client.models.cash_reserve_breakdown import CashReserveBreakdown
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CashReserveResponse(BaseModel):
    """
    CashReserveResponse
    """ # noqa: E501
    enforced: StrictBool = Field(description="Whether the minimum cash reserve guard is active in this environment.")
    available_usd: StrictStr = Field(description="The user's currently available USD balance in their Global Account.")
    committed_usd: StrictStr = Field(description="USD still counted in available_usd but already claimed by the user's open market buy orders on the Global Account, which reserve no funds at submission time. The reserve is evaluated against available_usd minus committed_usd.")
    required_usd: StrictStr = Field(description="The user's minimum USD cash reserve requirement.")
    satisfied: StrictBool = Field(description="Whether available_usd minus committed_usd is at least required_usd.")
    breakdown: CashReserveBreakdown
    __properties: ClassVar[List[str]] = ["enforced", "available_usd", "committed_usd", "required_usd", "satisfied", "breakdown"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CashReserveResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of breakdown
        if self.breakdown:
            _dict['breakdown'] = self.breakdown.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CashReserveResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enforced": obj.get("enforced"),
            "available_usd": obj.get("available_usd"),
            "committed_usd": obj.get("committed_usd"),
            "required_usd": obj.get("required_usd"),
            "satisfied": obj.get("satisfied"),
            "breakdown": CashReserveBreakdown.from_dict(obj["breakdown"]) if obj.get("breakdown") is not None else None
        })
        return _obj


