# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClaimLeverageAccruedInterestReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position_id': 'str',
        'asset_id': 'str',
        'quantity': 'str'
    }

    attribute_map = {
        'position_id': 'position_id',
        'asset_id': 'asset_id',
        'quantity': 'quantity'
    }

    def __init__(self, position_id=None, asset_id=None, quantity=None):  # noqa: E501
        """ClaimLeverageAccruedInterestReq - a model defined in Swagger"""  # noqa: E501
        self._position_id = None
        self._asset_id = None
        self._quantity = None
        self.discriminator = None
        self.position_id = position_id
        self.asset_id = asset_id
        self.quantity = quantity

    @property
    def position_id(self):
        """Gets the position_id of this ClaimLeverageAccruedInterestReq.  # noqa: E501


        :return: The position_id of this ClaimLeverageAccruedInterestReq.  # noqa: E501
        :rtype: str
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this ClaimLeverageAccruedInterestReq.


        :param position_id: The position_id of this ClaimLeverageAccruedInterestReq.  # noqa: E501
        :type: str
        """
        if position_id is None:
            raise ValueError("Invalid value for `position_id`, must not be `None`")  # noqa: E501

        self._position_id = position_id

    @property
    def asset_id(self):
        """Gets the asset_id of this ClaimLeverageAccruedInterestReq.  # noqa: E501


        :return: The asset_id of this ClaimLeverageAccruedInterestReq.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this ClaimLeverageAccruedInterestReq.


        :param asset_id: The asset_id of this ClaimLeverageAccruedInterestReq.  # noqa: E501
        :type: str
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")  # noqa: E501

        self._asset_id = asset_id

    @property
    def quantity(self):
        """Gets the quantity of this ClaimLeverageAccruedInterestReq.  # noqa: E501


        :return: The quantity of this ClaimLeverageAccruedInterestReq.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ClaimLeverageAccruedInterestReq.


        :param quantity: The quantity of this ClaimLeverageAccruedInterestReq.  # noqa: E501
        :type: str
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClaimLeverageAccruedInterestReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClaimLeverageAccruedInterestReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
