# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateOrderBookRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_asset_id': 'str',
        'display_name': 'str',
        'fee_factor': 'float',
        'initial_assets_ratio': 'float',
        'maturity_at': 'datetime',
        'price_display_multiplier': 'float',
        'quote_asset_id': 'str',
        'status': 'str',
        'tick_size': 'float',
        'base_quantity': 'float',
        'quote_quantity': 'float',
        'shares_asset_id': 'str'
    }

    attribute_map = {
        'base_asset_id': 'base_asset_id',
        'display_name': 'display_name',
        'fee_factor': 'fee_factor',
        'initial_assets_ratio': 'initial_assets_ratio',
        'maturity_at': 'maturity_at',
        'price_display_multiplier': 'price_display_multiplier',
        'quote_asset_id': 'quote_asset_id',
        'status': 'status',
        'tick_size': 'tick_size',
        'base_quantity': 'base_quantity',
        'quote_quantity': 'quote_quantity',
        'shares_asset_id': 'shares_asset_id'
    }

    def __init__(self, base_asset_id=None, display_name=None, fee_factor=None, initial_assets_ratio=None, maturity_at=None, price_display_multiplier=None, quote_asset_id=None, status=None, tick_size=None, base_quantity=None, quote_quantity=None, shares_asset_id=None):  # noqa: E501
        """CreateOrderBookRequest - a model defined in Swagger"""  # noqa: E501
        self._base_asset_id = None
        self._display_name = None
        self._fee_factor = None
        self._initial_assets_ratio = None
        self._maturity_at = None
        self._price_display_multiplier = None
        self._quote_asset_id = None
        self._status = None
        self._tick_size = None
        self._base_quantity = None
        self._quote_quantity = None
        self._shares_asset_id = None
        self.discriminator = None
        if base_asset_id is not None:
            self.base_asset_id = base_asset_id
        if display_name is not None:
            self.display_name = display_name
        if fee_factor is not None:
            self.fee_factor = fee_factor
        if initial_assets_ratio is not None:
            self.initial_assets_ratio = initial_assets_ratio
        if maturity_at is not None:
            self.maturity_at = maturity_at
        if price_display_multiplier is not None:
            self.price_display_multiplier = price_display_multiplier
        if quote_asset_id is not None:
            self.quote_asset_id = quote_asset_id
        if status is not None:
            self.status = status
        if tick_size is not None:
            self.tick_size = tick_size
        if base_quantity is not None:
            self.base_quantity = base_quantity
        if quote_quantity is not None:
            self.quote_quantity = quote_quantity
        if shares_asset_id is not None:
            self.shares_asset_id = shares_asset_id

    @property
    def base_asset_id(self):
        """Gets the base_asset_id of this CreateOrderBookRequest.  # noqa: E501


        :return: The base_asset_id of this CreateOrderBookRequest.  # noqa: E501
        :rtype: str
        """
        return self._base_asset_id

    @base_asset_id.setter
    def base_asset_id(self, base_asset_id):
        """Sets the base_asset_id of this CreateOrderBookRequest.


        :param base_asset_id: The base_asset_id of this CreateOrderBookRequest.  # noqa: E501
        :type: str
        """

        self._base_asset_id = base_asset_id

    @property
    def display_name(self):
        """Gets the display_name of this CreateOrderBookRequest.  # noqa: E501


        :return: The display_name of this CreateOrderBookRequest.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this CreateOrderBookRequest.


        :param display_name: The display_name of this CreateOrderBookRequest.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def fee_factor(self):
        """Gets the fee_factor of this CreateOrderBookRequest.  # noqa: E501


        :return: The fee_factor of this CreateOrderBookRequest.  # noqa: E501
        :rtype: float
        """
        return self._fee_factor

    @fee_factor.setter
    def fee_factor(self, fee_factor):
        """Sets the fee_factor of this CreateOrderBookRequest.


        :param fee_factor: The fee_factor of this CreateOrderBookRequest.  # noqa: E501
        :type: float
        """

        self._fee_factor = fee_factor

    @property
    def initial_assets_ratio(self):
        """Gets the initial_assets_ratio of this CreateOrderBookRequest.  # noqa: E501


        :return: The initial_assets_ratio of this CreateOrderBookRequest.  # noqa: E501
        :rtype: float
        """
        return self._initial_assets_ratio

    @initial_assets_ratio.setter
    def initial_assets_ratio(self, initial_assets_ratio):
        """Sets the initial_assets_ratio of this CreateOrderBookRequest.


        :param initial_assets_ratio: The initial_assets_ratio of this CreateOrderBookRequest.  # noqa: E501
        :type: float
        """

        self._initial_assets_ratio = initial_assets_ratio

    @property
    def maturity_at(self):
        """Gets the maturity_at of this CreateOrderBookRequest.  # noqa: E501


        :return: The maturity_at of this CreateOrderBookRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._maturity_at

    @maturity_at.setter
    def maturity_at(self, maturity_at):
        """Sets the maturity_at of this CreateOrderBookRequest.


        :param maturity_at: The maturity_at of this CreateOrderBookRequest.  # noqa: E501
        :type: datetime
        """

        self._maturity_at = maturity_at

    @property
    def price_display_multiplier(self):
        """Gets the price_display_multiplier of this CreateOrderBookRequest.  # noqa: E501


        :return: The price_display_multiplier of this CreateOrderBookRequest.  # noqa: E501
        :rtype: float
        """
        return self._price_display_multiplier

    @price_display_multiplier.setter
    def price_display_multiplier(self, price_display_multiplier):
        """Sets the price_display_multiplier of this CreateOrderBookRequest.


        :param price_display_multiplier: The price_display_multiplier of this CreateOrderBookRequest.  # noqa: E501
        :type: float
        """

        self._price_display_multiplier = price_display_multiplier

    @property
    def quote_asset_id(self):
        """Gets the quote_asset_id of this CreateOrderBookRequest.  # noqa: E501


        :return: The quote_asset_id of this CreateOrderBookRequest.  # noqa: E501
        :rtype: str
        """
        return self._quote_asset_id

    @quote_asset_id.setter
    def quote_asset_id(self, quote_asset_id):
        """Sets the quote_asset_id of this CreateOrderBookRequest.


        :param quote_asset_id: The quote_asset_id of this CreateOrderBookRequest.  # noqa: E501
        :type: str
        """

        self._quote_asset_id = quote_asset_id

    @property
    def status(self):
        """Gets the status of this CreateOrderBookRequest.  # noqa: E501


        :return: The status of this CreateOrderBookRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CreateOrderBookRequest.


        :param status: The status of this CreateOrderBookRequest.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def tick_size(self):
        """Gets the tick_size of this CreateOrderBookRequest.  # noqa: E501


        :return: The tick_size of this CreateOrderBookRequest.  # noqa: E501
        :rtype: float
        """
        return self._tick_size

    @tick_size.setter
    def tick_size(self, tick_size):
        """Sets the tick_size of this CreateOrderBookRequest.


        :param tick_size: The tick_size of this CreateOrderBookRequest.  # noqa: E501
        :type: float
        """

        self._tick_size = tick_size

    @property
    def base_quantity(self):
        """Gets the base_quantity of this CreateOrderBookRequest.  # noqa: E501


        :return: The base_quantity of this CreateOrderBookRequest.  # noqa: E501
        :rtype: float
        """
        return self._base_quantity

    @base_quantity.setter
    def base_quantity(self, base_quantity):
        """Sets the base_quantity of this CreateOrderBookRequest.


        :param base_quantity: The base_quantity of this CreateOrderBookRequest.  # noqa: E501
        :type: float
        """

        self._base_quantity = base_quantity

    @property
    def quote_quantity(self):
        """Gets the quote_quantity of this CreateOrderBookRequest.  # noqa: E501


        :return: The quote_quantity of this CreateOrderBookRequest.  # noqa: E501
        :rtype: float
        """
        return self._quote_quantity

    @quote_quantity.setter
    def quote_quantity(self, quote_quantity):
        """Sets the quote_quantity of this CreateOrderBookRequest.


        :param quote_quantity: The quote_quantity of this CreateOrderBookRequest.  # noqa: E501
        :type: float
        """

        self._quote_quantity = quote_quantity

    @property
    def shares_asset_id(self):
        """Gets the shares_asset_id of this CreateOrderBookRequest.  # noqa: E501


        :return: The shares_asset_id of this CreateOrderBookRequest.  # noqa: E501
        :rtype: str
        """
        return self._shares_asset_id

    @shares_asset_id.setter
    def shares_asset_id(self, shares_asset_id):
        """Sets the shares_asset_id of this CreateOrderBookRequest.


        :param shares_asset_id: The shares_asset_id of this CreateOrderBookRequest.  # noqa: E501
        :type: str
        """

        self._shares_asset_id = shares_asset_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateOrderBookRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateOrderBookRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
