# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateAffiliateProgramRequest(BaseModel):
    """
    CreateAffiliateProgramRequest
    """ # noqa: E501
    tenant_id: Annotated[str, Field(min_length=1, strict=True, max_length=256)] = Field(description="Owning tenant for administration. This does not define a referral destination.")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(description="No surrounding whitespace or control characters.")
    description: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default='', description="Omitted or null defaults to an empty description.")
    is_active: Optional[StrictBool] = Field(default=False, description="Inactive programs retain registrations, but cannot issue or resolve codes. Set true to create an active program.")
    __properties: ClassVar[List[str]] = ["tenant_id", "name", "description", "is_active"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAffiliateProgramRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAffiliateProgramRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenant_id": obj.get("tenant_id"),
            "name": obj.get("name"),
            "description": obj.get("description") if obj.get("description") is not None else '',
            "is_active": obj.get("is_active") if obj.get("is_active") is not None else False
        })
        return _obj


