# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateOrderRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantity': 'str',
        'inverse_leverage': 'str',
        'price': 'str',
        'kind': 'OrderKind',
        'side': 'Side',
        'from_global_position': 'bool',
        'order_book_id': 'str',
        'order_modifiers': 'list[OrderModifierKind]',
        'good_till_date': 'datetime',
        'trigger_price': 'str',
        'trigger_type': 'TriggerType'
    }

    attribute_map = {
        'quantity': 'quantity',
        'inverse_leverage': 'inverse_leverage',
        'price': 'price',
        'kind': 'kind',
        'side': 'side',
        'from_global_position': 'from_global_position',
        'order_book_id': 'order_book_id',
        'order_modifiers': 'order_modifiers',
        'good_till_date': 'good_till_date',
        'trigger_price': 'trigger_price',
        'trigger_type': 'trigger_type'
    }

    def __init__(self, quantity=None, inverse_leverage=None, price=None, kind=None, side=None, from_global_position=None, order_book_id=None, order_modifiers=None, good_till_date=None, trigger_price=None, trigger_type=None):  # noqa: E501
        """CreateOrderRequest - a model defined in Swagger"""  # noqa: E501
        self._quantity = None
        self._inverse_leverage = None
        self._price = None
        self._kind = None
        self._side = None
        self._from_global_position = None
        self._order_book_id = None
        self._order_modifiers = None
        self._good_till_date = None
        self._trigger_price = None
        self._trigger_type = None
        self.discriminator = None
        self.quantity = quantity
        self.inverse_leverage = inverse_leverage
        if price is not None:
            self.price = price
        self.kind = kind
        self.side = side
        self.from_global_position = from_global_position
        self.order_book_id = order_book_id
        if order_modifiers is not None:
            self.order_modifiers = order_modifiers
        if good_till_date is not None:
            self.good_till_date = good_till_date
        if trigger_price is not None:
            self.trigger_price = trigger_price
        if trigger_type is not None:
            self.trigger_type = trigger_type

    @property
    def quantity(self):
        """Gets the quantity of this CreateOrderRequest.  # noqa: E501


        :return: The quantity of this CreateOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this CreateOrderRequest.


        :param quantity: The quantity of this CreateOrderRequest.  # noqa: E501
        :type: str
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def inverse_leverage(self):
        """Gets the inverse_leverage of this CreateOrderRequest.  # noqa: E501


        :return: The inverse_leverage of this CreateOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._inverse_leverage

    @inverse_leverage.setter
    def inverse_leverage(self, inverse_leverage):
        """Sets the inverse_leverage of this CreateOrderRequest.


        :param inverse_leverage: The inverse_leverage of this CreateOrderRequest.  # noqa: E501
        :type: str
        """
        if inverse_leverage is None:
            raise ValueError("Invalid value for `inverse_leverage`, must not be `None`")  # noqa: E501

        self._inverse_leverage = inverse_leverage

    @property
    def price(self):
        """Gets the price of this CreateOrderRequest.  # noqa: E501


        :return: The price of this CreateOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this CreateOrderRequest.


        :param price: The price of this CreateOrderRequest.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def kind(self):
        """Gets the kind of this CreateOrderRequest.  # noqa: E501


        :return: The kind of this CreateOrderRequest.  # noqa: E501
        :rtype: OrderKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this CreateOrderRequest.


        :param kind: The kind of this CreateOrderRequest.  # noqa: E501
        :type: OrderKind
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def side(self):
        """Gets the side of this CreateOrderRequest.  # noqa: E501


        :return: The side of this CreateOrderRequest.  # noqa: E501
        :rtype: Side
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this CreateOrderRequest.


        :param side: The side of this CreateOrderRequest.  # noqa: E501
        :type: Side
        """
        if side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side

    @property
    def from_global_position(self):
        """Gets the from_global_position of this CreateOrderRequest.  # noqa: E501

        use global position for the order or isolated. required.  # noqa: E501

        :return: The from_global_position of this CreateOrderRequest.  # noqa: E501
        :rtype: bool
        """
        return self._from_global_position

    @from_global_position.setter
    def from_global_position(self, from_global_position):
        """Sets the from_global_position of this CreateOrderRequest.

        use global position for the order or isolated. required.  # noqa: E501

        :param from_global_position: The from_global_position of this CreateOrderRequest.  # noqa: E501
        :type: bool
        """
        if from_global_position is None:
            raise ValueError("Invalid value for `from_global_position`, must not be `None`")  # noqa: E501

        self._from_global_position = from_global_position

    @property
    def order_book_id(self):
        """Gets the order_book_id of this CreateOrderRequest.  # noqa: E501

        Required: the order book to submit the order to  # noqa: E501

        :return: The order_book_id of this CreateOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._order_book_id

    @order_book_id.setter
    def order_book_id(self, order_book_id):
        """Sets the order_book_id of this CreateOrderRequest.

        Required: the order book to submit the order to  # noqa: E501

        :param order_book_id: The order_book_id of this CreateOrderRequest.  # noqa: E501
        :type: str
        """
        if order_book_id is None:
            raise ValueError("Invalid value for `order_book_id`, must not be `None`")  # noqa: E501

        self._order_book_id = order_book_id

    @property
    def order_modifiers(self):
        """Gets the order_modifiers of this CreateOrderRequest.  # noqa: E501


        :return: The order_modifiers of this CreateOrderRequest.  # noqa: E501
        :rtype: list[OrderModifierKind]
        """
        return self._order_modifiers

    @order_modifiers.setter
    def order_modifiers(self, order_modifiers):
        """Sets the order_modifiers of this CreateOrderRequest.


        :param order_modifiers: The order_modifiers of this CreateOrderRequest.  # noqa: E501
        :type: list[OrderModifierKind]
        """

        self._order_modifiers = order_modifiers

    @property
    def good_till_date(self):
        """Gets the good_till_date of this CreateOrderRequest.  # noqa: E501


        :return: The good_till_date of this CreateOrderRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._good_till_date

    @good_till_date.setter
    def good_till_date(self, good_till_date):
        """Sets the good_till_date of this CreateOrderRequest.


        :param good_till_date: The good_till_date of this CreateOrderRequest.  # noqa: E501
        :type: datetime
        """

        self._good_till_date = good_till_date

    @property
    def trigger_price(self):
        """Gets the trigger_price of this CreateOrderRequest.  # noqa: E501


        :return: The trigger_price of this CreateOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._trigger_price

    @trigger_price.setter
    def trigger_price(self, trigger_price):
        """Sets the trigger_price of this CreateOrderRequest.


        :param trigger_price: The trigger_price of this CreateOrderRequest.  # noqa: E501
        :type: str
        """

        self._trigger_price = trigger_price

    @property
    def trigger_type(self):
        """Gets the trigger_type of this CreateOrderRequest.  # noqa: E501


        :return: The trigger_type of this CreateOrderRequest.  # noqa: E501
        :rtype: TriggerType
        """
        return self._trigger_type

    @trigger_type.setter
    def trigger_type(self, trigger_type):
        """Sets the trigger_type of this CreateOrderRequest.


        :param trigger_type: The trigger_type of this CreateOrderRequest.  # noqa: E501
        :type: TriggerType
        """

        self._trigger_type = trigger_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateOrderRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateOrderRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
