# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateBotResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bot_id': 'str',
        'bot_name': 'str'
    }

    attribute_map = {
        'bot_id': 'bot_id',
        'bot_name': 'bot_name'
    }

    def __init__(self, bot_id=None, bot_name=None):  # noqa: E501
        """CreateBotResponse - a model defined in Swagger"""  # noqa: E501
        self._bot_id = None
        self._bot_name = None
        self.discriminator = None
        if bot_id is not None:
            self.bot_id = bot_id
        if bot_name is not None:
            self.bot_name = bot_name

    @property
    def bot_id(self):
        """Gets the bot_id of this CreateBotResponse.  # noqa: E501

        Created bot ID  # noqa: E501

        :return: The bot_id of this CreateBotResponse.  # noqa: E501
        :rtype: str
        """
        return self._bot_id

    @bot_id.setter
    def bot_id(self, bot_id):
        """Sets the bot_id of this CreateBotResponse.

        Created bot ID  # noqa: E501

        :param bot_id: The bot_id of this CreateBotResponse.  # noqa: E501
        :type: str
        """

        self._bot_id = bot_id

    @property
    def bot_name(self):
        """Gets the bot_name of this CreateBotResponse.  # noqa: E501

        Bot name  # noqa: E501

        :return: The bot_name of this CreateBotResponse.  # noqa: E501
        :rtype: str
        """
        return self._bot_name

    @bot_name.setter
    def bot_name(self, bot_name):
        """Sets the bot_name of this CreateBotResponse.

        Bot name  # noqa: E501

        :param bot_name: The bot_name of this CreateBotResponse.  # noqa: E501
        :type: str
        """

        self._bot_name = bot_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateBotResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBotResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
