# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FeeQuoteResponse(BaseModel):
    """
    The estimated network fee to withdraw USDC via web3, alongside a signed, TTL-bound quote token the client submits with a later withdrawal so the server can validate the fee it was quoted.
    """ # noqa: E501
    to: StrictStr = Field(description="The withdrawal destination address, echoed from the request.")
    quantity: StrictStr = Field(description="Human-decimal USDC withdrawal quantity, echoed from the request.")
    fee: StrictStr = Field(description="The estimated network fee, in human USDC.")
    fee_base_units: StrictStr = Field(description="The estimated network fee, in micro-USDC base units.")
    chain_id: StrictStr = Field(description="EVM chain ID the quote was computed for.")
    quote_token: StrictStr = Field(description="Signed, TTL-bound quote token to submit with a later withdrawal so the server can validate the fee it was quoted.")
    expires_at: datetime = Field(description="When the quote token expires.")
    __properties: ClassVar[List[str]] = ["to", "quantity", "fee", "fee_base_units", "chain_id", "quote_token", "expires_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeeQuoteResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeeQuoteResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "to": obj.get("to"),
            "quantity": obj.get("quantity"),
            "fee": obj.get("fee"),
            "fee_base_units": obj.get("fee_base_units"),
            "chain_id": obj.get("chain_id"),
            "quote_token": obj.get("quote_token"),
            "expires_at": obj.get("expires_at")
        })
        return _obj


