# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IsolatedCollateral(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'global_position_id': 'str',
        'isolated_position_id': 'str',
        'transaction_id': 'str',
        'asset_id': 'str',
        'quantity': 'str'
    }

    attribute_map = {
        'global_position_id': 'global_position_id',
        'isolated_position_id': 'isolated_position_id',
        'transaction_id': 'transaction_id',
        'asset_id': 'asset_id',
        'quantity': 'quantity'
    }

    def __init__(self, global_position_id=None, isolated_position_id=None, transaction_id=None, asset_id=None, quantity=None):  # noqa: E501
        """IsolatedCollateral - a model defined in Swagger"""  # noqa: E501
        self._global_position_id = None
        self._isolated_position_id = None
        self._transaction_id = None
        self._asset_id = None
        self._quantity = None
        self.discriminator = None
        if global_position_id is not None:
            self.global_position_id = global_position_id
        if isolated_position_id is not None:
            self.isolated_position_id = isolated_position_id
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if asset_id is not None:
            self.asset_id = asset_id
        if quantity is not None:
            self.quantity = quantity

    @property
    def global_position_id(self):
        """Gets the global_position_id of this IsolatedCollateral.  # noqa: E501


        :return: The global_position_id of this IsolatedCollateral.  # noqa: E501
        :rtype: str
        """
        return self._global_position_id

    @global_position_id.setter
    def global_position_id(self, global_position_id):
        """Sets the global_position_id of this IsolatedCollateral.


        :param global_position_id: The global_position_id of this IsolatedCollateral.  # noqa: E501
        :type: str
        """

        self._global_position_id = global_position_id

    @property
    def isolated_position_id(self):
        """Gets the isolated_position_id of this IsolatedCollateral.  # noqa: E501


        :return: The isolated_position_id of this IsolatedCollateral.  # noqa: E501
        :rtype: str
        """
        return self._isolated_position_id

    @isolated_position_id.setter
    def isolated_position_id(self, isolated_position_id):
        """Sets the isolated_position_id of this IsolatedCollateral.


        :param isolated_position_id: The isolated_position_id of this IsolatedCollateral.  # noqa: E501
        :type: str
        """

        self._isolated_position_id = isolated_position_id

    @property
    def transaction_id(self):
        """Gets the transaction_id of this IsolatedCollateral.  # noqa: E501


        :return: The transaction_id of this IsolatedCollateral.  # noqa: E501
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this IsolatedCollateral.


        :param transaction_id: The transaction_id of this IsolatedCollateral.  # noqa: E501
        :type: str
        """

        self._transaction_id = transaction_id

    @property
    def asset_id(self):
        """Gets the asset_id of this IsolatedCollateral.  # noqa: E501


        :return: The asset_id of this IsolatedCollateral.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this IsolatedCollateral.


        :param asset_id: The asset_id of this IsolatedCollateral.  # noqa: E501
        :type: str
        """

        self._asset_id = asset_id

    @property
    def quantity(self):
        """Gets the quantity of this IsolatedCollateral.  # noqa: E501


        :return: The quantity of this IsolatedCollateral.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this IsolatedCollateral.


        :param quantity: The quantity of this IsolatedCollateral.  # noqa: E501
        :type: str
        """

        self._quantity = quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IsolatedCollateral, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IsolatedCollateral):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
