# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from dora_client.models.promo_source_type import PromoSourceType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IssuePromoLinkBatchRequest(BaseModel):
    """
    IssuePromoLinkBatchRequest
    """ # noqa: E501
    source_type: PromoSourceType
    source_id: Annotated[str, Field(strict=True)]
    source_name: Optional[Annotated[str, Field(strict=True, max_length=256)]] = None
    allocation: Annotated[int, Field(strict=True, ge=1)] = Field(description="Cannot exceed the configured max_links_per_batch or remaining campaign capacity.")
    note: Optional[Annotated[str, Field(strict=True, max_length=512)]] = None
    expires_at: Optional[datetime] = Field(default=None, description="Defaults to challenge end and must fall between challenge start and end in the future.")
    __properties: ClassVar[List[str]] = ["source_type", "source_id", "source_name", "allocation", "note", "expires_at"]

    @field_validator('source_id')
    def source_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Z0-9][A-Z0-9_-]{0,63}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9][A-Z0-9_-]{0,63}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IssuePromoLinkBatchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IssuePromoLinkBatchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_type": obj.get("source_type"),
            "source_id": obj.get("source_id"),
            "source_name": obj.get("source_name"),
            "allocation": obj.get("allocation"),
            "note": obj.get("note"),
            "expires_at": obj.get("expires_at")
        })
        return _obj


