# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LeverageUtilization(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_id': 'str',
        'avg_utilization': 'str',
        'start_time': 'datetime',
        'end_time': 'datetime'
    }

    attribute_map = {
        'asset_id': 'asset_id',
        'avg_utilization': 'avg_utilization',
        'start_time': 'start_time',
        'end_time': 'end_time'
    }

    def __init__(self, asset_id=None, avg_utilization=None, start_time=None, end_time=None):  # noqa: E501
        """LeverageUtilization - a model defined in Swagger"""  # noqa: E501
        self._asset_id = None
        self._avg_utilization = None
        self._start_time = None
        self._end_time = None
        self.discriminator = None
        if asset_id is not None:
            self.asset_id = asset_id
        if avg_utilization is not None:
            self.avg_utilization = avg_utilization
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time

    @property
    def asset_id(self):
        """Gets the asset_id of this LeverageUtilization.  # noqa: E501


        :return: The asset_id of this LeverageUtilization.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this LeverageUtilization.


        :param asset_id: The asset_id of this LeverageUtilization.  # noqa: E501
        :type: str
        """

        self._asset_id = asset_id

    @property
    def avg_utilization(self):
        """Gets the avg_utilization of this LeverageUtilization.  # noqa: E501


        :return: The avg_utilization of this LeverageUtilization.  # noqa: E501
        :rtype: str
        """
        return self._avg_utilization

    @avg_utilization.setter
    def avg_utilization(self, avg_utilization):
        """Sets the avg_utilization of this LeverageUtilization.


        :param avg_utilization: The avg_utilization of this LeverageUtilization.  # noqa: E501
        :type: str
        """

        self._avg_utilization = avg_utilization

    @property
    def start_time(self):
        """Gets the start_time of this LeverageUtilization.  # noqa: E501


        :return: The start_time of this LeverageUtilization.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this LeverageUtilization.


        :param start_time: The start_time of this LeverageUtilization.  # noqa: E501
        :type: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this LeverageUtilization.  # noqa: E501


        :return: The end_time of this LeverageUtilization.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this LeverageUtilization.


        :param end_time: The end_time of this LeverageUtilization.  # noqa: E501
        :type: datetime
        """

        self._end_time = end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LeverageUtilization, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LeverageUtilization):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
