# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LiquidityRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_book_id': 'str',
        'position_id': 'str',
        'quantity': 'str'
    }

    attribute_map = {
        'order_book_id': 'order_book_id',
        'position_id': 'position_id',
        'quantity': 'quantity'
    }

    def __init__(self, order_book_id=None, position_id=None, quantity=None):  # noqa: E501
        """LiquidityRequest - a model defined in Swagger"""  # noqa: E501
        self._order_book_id = None
        self._position_id = None
        self._quantity = None
        self.discriminator = None
        if order_book_id is not None:
            self.order_book_id = order_book_id
        if position_id is not None:
            self.position_id = position_id
        if quantity is not None:
            self.quantity = quantity

    @property
    def order_book_id(self):
        """Gets the order_book_id of this LiquidityRequest.  # noqa: E501


        :return: The order_book_id of this LiquidityRequest.  # noqa: E501
        :rtype: str
        """
        return self._order_book_id

    @order_book_id.setter
    def order_book_id(self, order_book_id):
        """Sets the order_book_id of this LiquidityRequest.


        :param order_book_id: The order_book_id of this LiquidityRequest.  # noqa: E501
        :type: str
        """

        self._order_book_id = order_book_id

    @property
    def position_id(self):
        """Gets the position_id of this LiquidityRequest.  # noqa: E501


        :return: The position_id of this LiquidityRequest.  # noqa: E501
        :rtype: str
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this LiquidityRequest.


        :param position_id: The position_id of this LiquidityRequest.  # noqa: E501
        :type: str
        """

        self._position_id = position_id

    @property
    def quantity(self):
        """Gets the quantity of this LiquidityRequest.  # noqa: E501


        :return: The quantity of this LiquidityRequest.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this LiquidityRequest.


        :param quantity: The quantity of this LiquidityRequest.  # noqa: E501
        :type: str
        """

        self._quantity = quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LiquidityRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LiquidityRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
