# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LiquidityResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_book_id': 'str',
        'position_id': 'str',
        'transaction_id': 'str',
        'base_quantity': 'str',
        'quote_quantity': 'str',
        'shares_quantity': 'str'
    }

    attribute_map = {
        'order_book_id': 'order_book_id',
        'position_id': 'position_id',
        'transaction_id': 'transaction_id',
        'base_quantity': 'base_quantity',
        'quote_quantity': 'quote_quantity',
        'shares_quantity': 'shares_quantity'
    }

    def __init__(self, order_book_id=None, position_id=None, transaction_id=None, base_quantity=None, quote_quantity=None, shares_quantity=None):  # noqa: E501
        """LiquidityResponse - a model defined in Swagger"""  # noqa: E501
        self._order_book_id = None
        self._position_id = None
        self._transaction_id = None
        self._base_quantity = None
        self._quote_quantity = None
        self._shares_quantity = None
        self.discriminator = None
        if order_book_id is not None:
            self.order_book_id = order_book_id
        if position_id is not None:
            self.position_id = position_id
        if transaction_id is not None:
            self.transaction_id = transaction_id
        if base_quantity is not None:
            self.base_quantity = base_quantity
        if quote_quantity is not None:
            self.quote_quantity = quote_quantity
        if shares_quantity is not None:
            self.shares_quantity = shares_quantity

    @property
    def order_book_id(self):
        """Gets the order_book_id of this LiquidityResponse.  # noqa: E501


        :return: The order_book_id of this LiquidityResponse.  # noqa: E501
        :rtype: str
        """
        return self._order_book_id

    @order_book_id.setter
    def order_book_id(self, order_book_id):
        """Sets the order_book_id of this LiquidityResponse.


        :param order_book_id: The order_book_id of this LiquidityResponse.  # noqa: E501
        :type: str
        """

        self._order_book_id = order_book_id

    @property
    def position_id(self):
        """Gets the position_id of this LiquidityResponse.  # noqa: E501


        :return: The position_id of this LiquidityResponse.  # noqa: E501
        :rtype: str
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this LiquidityResponse.


        :param position_id: The position_id of this LiquidityResponse.  # noqa: E501
        :type: str
        """

        self._position_id = position_id

    @property
    def transaction_id(self):
        """Gets the transaction_id of this LiquidityResponse.  # noqa: E501


        :return: The transaction_id of this LiquidityResponse.  # noqa: E501
        :rtype: str
        """
        return self._transaction_id

    @transaction_id.setter
    def transaction_id(self, transaction_id):
        """Sets the transaction_id of this LiquidityResponse.


        :param transaction_id: The transaction_id of this LiquidityResponse.  # noqa: E501
        :type: str
        """

        self._transaction_id = transaction_id

    @property
    def base_quantity(self):
        """Gets the base_quantity of this LiquidityResponse.  # noqa: E501


        :return: The base_quantity of this LiquidityResponse.  # noqa: E501
        :rtype: str
        """
        return self._base_quantity

    @base_quantity.setter
    def base_quantity(self, base_quantity):
        """Sets the base_quantity of this LiquidityResponse.


        :param base_quantity: The base_quantity of this LiquidityResponse.  # noqa: E501
        :type: str
        """

        self._base_quantity = base_quantity

    @property
    def quote_quantity(self):
        """Gets the quote_quantity of this LiquidityResponse.  # noqa: E501


        :return: The quote_quantity of this LiquidityResponse.  # noqa: E501
        :rtype: str
        """
        return self._quote_quantity

    @quote_quantity.setter
    def quote_quantity(self, quote_quantity):
        """Sets the quote_quantity of this LiquidityResponse.


        :param quote_quantity: The quote_quantity of this LiquidityResponse.  # noqa: E501
        :type: str
        """

        self._quote_quantity = quote_quantity

    @property
    def shares_quantity(self):
        """Gets the shares_quantity of this LiquidityResponse.  # noqa: E501


        :return: The shares_quantity of this LiquidityResponse.  # noqa: E501
        :rtype: str
        """
        return self._shares_quantity

    @shares_quantity.setter
    def shares_quantity(self, shares_quantity):
        """Sets the shares_quantity of this LiquidityResponse.


        :param shares_quantity: The shares_quantity of this LiquidityResponse.  # noqa: E501
        :type: str
        """

        self._shares_quantity = shares_quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LiquidityResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LiquidityResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
