# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListBotStrategiesMarketStrategies(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'strategy_id': 'str',
        'strategy_name': 'str',
        'c0': 'str',
        'c1': 'str',
        'c2': 'str',
        'levels': 'int',
        'spread': 'str'
    }

    attribute_map = {
        'strategy_id': 'strategy_id',
        'strategy_name': 'strategy_name',
        'c0': 'c0',
        'c1': 'c1',
        'c2': 'c2',
        'levels': 'levels',
        'spread': 'spread'
    }

    def __init__(self, strategy_id=None, strategy_name=None, c0=None, c1=None, c2=None, levels=None, spread=None):  # noqa: E501
        """ListBotStrategiesMarketStrategies - a model defined in Swagger"""  # noqa: E501
        self._strategy_id = None
        self._strategy_name = None
        self._c0 = None
        self._c1 = None
        self._c2 = None
        self._levels = None
        self._spread = None
        self.discriminator = None
        self.strategy_id = strategy_id
        self.strategy_name = strategy_name
        self.c0 = c0
        self.c1 = c1
        self.c2 = c2
        self.levels = levels
        self.spread = spread

    @property
    def strategy_id(self):
        """Gets the strategy_id of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The strategy_id of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: str
        """
        return self._strategy_id

    @strategy_id.setter
    def strategy_id(self, strategy_id):
        """Sets the strategy_id of this ListBotStrategiesMarketStrategies.


        :param strategy_id: The strategy_id of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: str
        """
        if strategy_id is None:
            raise ValueError("Invalid value for `strategy_id`, must not be `None`")  # noqa: E501

        self._strategy_id = strategy_id

    @property
    def strategy_name(self):
        """Gets the strategy_name of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The strategy_name of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: str
        """
        return self._strategy_name

    @strategy_name.setter
    def strategy_name(self, strategy_name):
        """Sets the strategy_name of this ListBotStrategiesMarketStrategies.


        :param strategy_name: The strategy_name of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: str
        """
        if strategy_name is None:
            raise ValueError("Invalid value for `strategy_name`, must not be `None`")  # noqa: E501

        self._strategy_name = strategy_name

    @property
    def c0(self):
        """Gets the c0 of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The c0 of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: str
        """
        return self._c0

    @c0.setter
    def c0(self, c0):
        """Sets the c0 of this ListBotStrategiesMarketStrategies.


        :param c0: The c0 of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: str
        """
        if c0 is None:
            raise ValueError("Invalid value for `c0`, must not be `None`")  # noqa: E501

        self._c0 = c0

    @property
    def c1(self):
        """Gets the c1 of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The c1 of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: str
        """
        return self._c1

    @c1.setter
    def c1(self, c1):
        """Sets the c1 of this ListBotStrategiesMarketStrategies.


        :param c1: The c1 of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: str
        """
        if c1 is None:
            raise ValueError("Invalid value for `c1`, must not be `None`")  # noqa: E501

        self._c1 = c1

    @property
    def c2(self):
        """Gets the c2 of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The c2 of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: str
        """
        return self._c2

    @c2.setter
    def c2(self, c2):
        """Sets the c2 of this ListBotStrategiesMarketStrategies.


        :param c2: The c2 of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: str
        """
        if c2 is None:
            raise ValueError("Invalid value for `c2`, must not be `None`")  # noqa: E501

        self._c2 = c2

    @property
    def levels(self):
        """Gets the levels of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The levels of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: int
        """
        return self._levels

    @levels.setter
    def levels(self, levels):
        """Sets the levels of this ListBotStrategiesMarketStrategies.


        :param levels: The levels of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: int
        """
        if levels is None:
            raise ValueError("Invalid value for `levels`, must not be `None`")  # noqa: E501

        self._levels = levels

    @property
    def spread(self):
        """Gets the spread of this ListBotStrategiesMarketStrategies.  # noqa: E501


        :return: The spread of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :rtype: str
        """
        return self._spread

    @spread.setter
    def spread(self, spread):
        """Sets the spread of this ListBotStrategiesMarketStrategies.


        :param spread: The spread of this ListBotStrategiesMarketStrategies.  # noqa: E501
        :type: str
        """
        if spread is None:
            raise ValueError("Invalid value for `spread`, must not be `None`")  # noqa: E501

        self._spread = spread

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListBotStrategiesMarketStrategies, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListBotStrategiesMarketStrategies):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
