# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListBotStrategiesTradingStrategies(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'strategy_id': 'str',
        'strategy_name': 'str',
        'created_at': 'datetime',
        'trades': 'list[ListBotStrategiesTrades]'
    }

    attribute_map = {
        'strategy_id': 'strategy_id',
        'strategy_name': 'strategy_name',
        'created_at': 'created_at',
        'trades': 'trades'
    }

    def __init__(self, strategy_id=None, strategy_name=None, created_at=None, trades=None):  # noqa: E501
        """ListBotStrategiesTradingStrategies - a model defined in Swagger"""  # noqa: E501
        self._strategy_id = None
        self._strategy_name = None
        self._created_at = None
        self._trades = None
        self.discriminator = None
        self.strategy_id = strategy_id
        self.strategy_name = strategy_name
        self.created_at = created_at
        self.trades = trades

    @property
    def strategy_id(self):
        """Gets the strategy_id of this ListBotStrategiesTradingStrategies.  # noqa: E501


        :return: The strategy_id of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._strategy_id

    @strategy_id.setter
    def strategy_id(self, strategy_id):
        """Sets the strategy_id of this ListBotStrategiesTradingStrategies.


        :param strategy_id: The strategy_id of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :type: str
        """
        if strategy_id is None:
            raise ValueError("Invalid value for `strategy_id`, must not be `None`")  # noqa: E501

        self._strategy_id = strategy_id

    @property
    def strategy_name(self):
        """Gets the strategy_name of this ListBotStrategiesTradingStrategies.  # noqa: E501


        :return: The strategy_name of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._strategy_name

    @strategy_name.setter
    def strategy_name(self, strategy_name):
        """Sets the strategy_name of this ListBotStrategiesTradingStrategies.


        :param strategy_name: The strategy_name of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :type: str
        """
        if strategy_name is None:
            raise ValueError("Invalid value for `strategy_name`, must not be `None`")  # noqa: E501

        self._strategy_name = strategy_name

    @property
    def created_at(self):
        """Gets the created_at of this ListBotStrategiesTradingStrategies.  # noqa: E501


        :return: The created_at of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ListBotStrategiesTradingStrategies.


        :param created_at: The created_at of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def trades(self):
        """Gets the trades of this ListBotStrategiesTradingStrategies.  # noqa: E501


        :return: The trades of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :rtype: list[ListBotStrategiesTrades]
        """
        return self._trades

    @trades.setter
    def trades(self, trades):
        """Sets the trades of this ListBotStrategiesTradingStrategies.


        :param trades: The trades of this ListBotStrategiesTradingStrategies.  # noqa: E501
        :type: list[ListBotStrategiesTrades]
        """
        if trades is None:
            raise ValueError("Invalid value for `trades`, must not be `None`")  # noqa: E501

        self._trades = trades

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListBotStrategiesTradingStrategies, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListBotStrategiesTradingStrategies):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
