# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListBotStrategiesTrades(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantity': 'str',
        'side': 'str',
        'seq': 'int'
    }

    attribute_map = {
        'quantity': 'quantity',
        'side': 'side',
        'seq': 'seq'
    }

    def __init__(self, quantity=None, side=None, seq=None):  # noqa: E501
        """ListBotStrategiesTrades - a model defined in Swagger"""  # noqa: E501
        self._quantity = None
        self._side = None
        self._seq = None
        self.discriminator = None
        self.quantity = quantity
        self.side = side
        self.seq = seq

    @property
    def quantity(self):
        """Gets the quantity of this ListBotStrategiesTrades.  # noqa: E501


        :return: The quantity of this ListBotStrategiesTrades.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ListBotStrategiesTrades.


        :param quantity: The quantity of this ListBotStrategiesTrades.  # noqa: E501
        :type: str
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def side(self):
        """Gets the side of this ListBotStrategiesTrades.  # noqa: E501


        :return: The side of this ListBotStrategiesTrades.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this ListBotStrategiesTrades.


        :param side: The side of this ListBotStrategiesTrades.  # noqa: E501
        :type: str
        """
        if side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side

    @property
    def seq(self):
        """Gets the seq of this ListBotStrategiesTrades.  # noqa: E501


        :return: The seq of this ListBotStrategiesTrades.  # noqa: E501
        :rtype: int
        """
        return self._seq

    @seq.setter
    def seq(self, seq):
        """Sets the seq of this ListBotStrategiesTrades.


        :param seq: The seq of this ListBotStrategiesTrades.  # noqa: E501
        :type: int
        """
        if seq is None:
            raise ValueError("Invalid value for `seq`, must not be `None`")  # noqa: E501

        self._seq = seq

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListBotStrategiesTrades, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListBotStrategiesTrades):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
