# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListBotStrategiesPricingStrategies(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'strategy_id': 'str',
        'strategy_name': 'str',
        'max_rel_trade_vol': 'str',
        'rel_tol': 'str',
        'target_price': 'str'
    }

    attribute_map = {
        'strategy_id': 'strategy_id',
        'strategy_name': 'strategy_name',
        'max_rel_trade_vol': 'max_rel_trade_vol',
        'rel_tol': 'rel_tol',
        'target_price': 'target_price'
    }

    def __init__(self, strategy_id=None, strategy_name=None, max_rel_trade_vol=None, rel_tol=None, target_price=None):  # noqa: E501
        """ListBotStrategiesPricingStrategies - a model defined in Swagger"""  # noqa: E501
        self._strategy_id = None
        self._strategy_name = None
        self._max_rel_trade_vol = None
        self._rel_tol = None
        self._target_price = None
        self.discriminator = None
        self.strategy_id = strategy_id
        self.strategy_name = strategy_name
        self.max_rel_trade_vol = max_rel_trade_vol
        self.rel_tol = rel_tol
        self.target_price = target_price

    @property
    def strategy_id(self):
        """Gets the strategy_id of this ListBotStrategiesPricingStrategies.  # noqa: E501


        :return: The strategy_id of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._strategy_id

    @strategy_id.setter
    def strategy_id(self, strategy_id):
        """Sets the strategy_id of this ListBotStrategiesPricingStrategies.


        :param strategy_id: The strategy_id of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :type: str
        """
        if strategy_id is None:
            raise ValueError("Invalid value for `strategy_id`, must not be `None`")  # noqa: E501

        self._strategy_id = strategy_id

    @property
    def strategy_name(self):
        """Gets the strategy_name of this ListBotStrategiesPricingStrategies.  # noqa: E501


        :return: The strategy_name of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._strategy_name

    @strategy_name.setter
    def strategy_name(self, strategy_name):
        """Sets the strategy_name of this ListBotStrategiesPricingStrategies.


        :param strategy_name: The strategy_name of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :type: str
        """
        if strategy_name is None:
            raise ValueError("Invalid value for `strategy_name`, must not be `None`")  # noqa: E501

        self._strategy_name = strategy_name

    @property
    def max_rel_trade_vol(self):
        """Gets the max_rel_trade_vol of this ListBotStrategiesPricingStrategies.  # noqa: E501


        :return: The max_rel_trade_vol of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._max_rel_trade_vol

    @max_rel_trade_vol.setter
    def max_rel_trade_vol(self, max_rel_trade_vol):
        """Sets the max_rel_trade_vol of this ListBotStrategiesPricingStrategies.


        :param max_rel_trade_vol: The max_rel_trade_vol of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :type: str
        """
        if max_rel_trade_vol is None:
            raise ValueError("Invalid value for `max_rel_trade_vol`, must not be `None`")  # noqa: E501

        self._max_rel_trade_vol = max_rel_trade_vol

    @property
    def rel_tol(self):
        """Gets the rel_tol of this ListBotStrategiesPricingStrategies.  # noqa: E501


        :return: The rel_tol of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._rel_tol

    @rel_tol.setter
    def rel_tol(self, rel_tol):
        """Sets the rel_tol of this ListBotStrategiesPricingStrategies.


        :param rel_tol: The rel_tol of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :type: str
        """
        if rel_tol is None:
            raise ValueError("Invalid value for `rel_tol`, must not be `None`")  # noqa: E501

        self._rel_tol = rel_tol

    @property
    def target_price(self):
        """Gets the target_price of this ListBotStrategiesPricingStrategies.  # noqa: E501


        :return: The target_price of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :rtype: str
        """
        return self._target_price

    @target_price.setter
    def target_price(self, target_price):
        """Sets the target_price of this ListBotStrategiesPricingStrategies.


        :param target_price: The target_price of this ListBotStrategiesPricingStrategies.  # noqa: E501
        :type: str
        """
        if target_price is None:
            raise ValueError("Invalid value for `target_price`, must not be `None`")  # noqa: E501

        self._target_price = target_price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListBotStrategiesPricingStrategies, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListBotStrategiesPricingStrategies):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
