# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrderBook(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_book_id': 'str',
        'order_book_seq': 'int',
        'accumulated_fees_id': 'str',
        'base_quantity': 'float',
        'base_asset_id': 'str',
        'created_at': 'datetime',
        'display_name': 'str',
        'fee_factor': 'float',
        'initial_assets_ratio': 'float',
        'maturity_at': 'datetime',
        'price_display_multiplier': 'float',
        'quote_quantity': 'float',
        'quote_asset_id': 'str',
        'shares_quantity': 'float',
        'status': 'str',
        'tick_size': 'float',
        'updated_at': 'datetime',
        'halted_at': 'datetime',
        'terminated_at': 'datetime',
        'pool_updated_at': 'datetime',
        'pool_seq': 'int',
        'shares_asset_id': 'str'
    }

    attribute_map = {
        'order_book_id': 'order_book_id',
        'order_book_seq': 'order_book_seq',
        'accumulated_fees_id': 'accumulated_fees_id',
        'base_quantity': 'base_quantity',
        'base_asset_id': 'base_asset_id',
        'created_at': 'created_at',
        'display_name': 'display_name',
        'fee_factor': 'fee_factor',
        'initial_assets_ratio': 'initial_assets_ratio',
        'maturity_at': 'maturity_at',
        'price_display_multiplier': 'price_display_multiplier',
        'quote_quantity': 'quote_quantity',
        'quote_asset_id': 'quote_asset_id',
        'shares_quantity': 'shares_quantity',
        'status': 'status',
        'tick_size': 'tick_size',
        'updated_at': 'updated_at',
        'halted_at': 'halted_at',
        'terminated_at': 'terminated_at',
        'pool_updated_at': 'pool_updated_at',
        'pool_seq': 'pool_seq',
        'shares_asset_id': 'shares_asset_id'
    }

    def __init__(self, order_book_id=None, order_book_seq=None, accumulated_fees_id=None, base_quantity=None, base_asset_id=None, created_at=None, display_name=None, fee_factor=None, initial_assets_ratio=None, maturity_at=None, price_display_multiplier=None, quote_quantity=None, quote_asset_id=None, shares_quantity=None, status=None, tick_size=None, updated_at=None, halted_at=None, terminated_at=None, pool_updated_at=None, pool_seq=None, shares_asset_id=None):  # noqa: E501
        """OrderBook - a model defined in Swagger"""  # noqa: E501
        self._order_book_id = None
        self._order_book_seq = None
        self._accumulated_fees_id = None
        self._base_quantity = None
        self._base_asset_id = None
        self._created_at = None
        self._display_name = None
        self._fee_factor = None
        self._initial_assets_ratio = None
        self._maturity_at = None
        self._price_display_multiplier = None
        self._quote_quantity = None
        self._quote_asset_id = None
        self._shares_quantity = None
        self._status = None
        self._tick_size = None
        self._updated_at = None
        self._halted_at = None
        self._terminated_at = None
        self._pool_updated_at = None
        self._pool_seq = None
        self._shares_asset_id = None
        self.discriminator = None
        if order_book_id is not None:
            self.order_book_id = order_book_id
        if order_book_seq is not None:
            self.order_book_seq = order_book_seq
        if accumulated_fees_id is not None:
            self.accumulated_fees_id = accumulated_fees_id
        if base_quantity is not None:
            self.base_quantity = base_quantity
        if base_asset_id is not None:
            self.base_asset_id = base_asset_id
        if created_at is not None:
            self.created_at = created_at
        if display_name is not None:
            self.display_name = display_name
        if fee_factor is not None:
            self.fee_factor = fee_factor
        if initial_assets_ratio is not None:
            self.initial_assets_ratio = initial_assets_ratio
        if maturity_at is not None:
            self.maturity_at = maturity_at
        if price_display_multiplier is not None:
            self.price_display_multiplier = price_display_multiplier
        if quote_quantity is not None:
            self.quote_quantity = quote_quantity
        if quote_asset_id is not None:
            self.quote_asset_id = quote_asset_id
        if shares_quantity is not None:
            self.shares_quantity = shares_quantity
        if status is not None:
            self.status = status
        if tick_size is not None:
            self.tick_size = tick_size
        if updated_at is not None:
            self.updated_at = updated_at
        if halted_at is not None:
            self.halted_at = halted_at
        if terminated_at is not None:
            self.terminated_at = terminated_at
        if pool_updated_at is not None:
            self.pool_updated_at = pool_updated_at
        if pool_seq is not None:
            self.pool_seq = pool_seq
        if shares_asset_id is not None:
            self.shares_asset_id = shares_asset_id

    @property
    def order_book_id(self):
        """Gets the order_book_id of this OrderBook.  # noqa: E501


        :return: The order_book_id of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._order_book_id

    @order_book_id.setter
    def order_book_id(self, order_book_id):
        """Sets the order_book_id of this OrderBook.


        :param order_book_id: The order_book_id of this OrderBook.  # noqa: E501
        :type: str
        """

        self._order_book_id = order_book_id

    @property
    def order_book_seq(self):
        """Gets the order_book_seq of this OrderBook.  # noqa: E501


        :return: The order_book_seq of this OrderBook.  # noqa: E501
        :rtype: int
        """
        return self._order_book_seq

    @order_book_seq.setter
    def order_book_seq(self, order_book_seq):
        """Sets the order_book_seq of this OrderBook.


        :param order_book_seq: The order_book_seq of this OrderBook.  # noqa: E501
        :type: int
        """

        self._order_book_seq = order_book_seq

    @property
    def accumulated_fees_id(self):
        """Gets the accumulated_fees_id of this OrderBook.  # noqa: E501


        :return: The accumulated_fees_id of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._accumulated_fees_id

    @accumulated_fees_id.setter
    def accumulated_fees_id(self, accumulated_fees_id):
        """Sets the accumulated_fees_id of this OrderBook.


        :param accumulated_fees_id: The accumulated_fees_id of this OrderBook.  # noqa: E501
        :type: str
        """

        self._accumulated_fees_id = accumulated_fees_id

    @property
    def base_quantity(self):
        """Gets the base_quantity of this OrderBook.  # noqa: E501


        :return: The base_quantity of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._base_quantity

    @base_quantity.setter
    def base_quantity(self, base_quantity):
        """Sets the base_quantity of this OrderBook.


        :param base_quantity: The base_quantity of this OrderBook.  # noqa: E501
        :type: float
        """

        self._base_quantity = base_quantity

    @property
    def base_asset_id(self):
        """Gets the base_asset_id of this OrderBook.  # noqa: E501


        :return: The base_asset_id of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._base_asset_id

    @base_asset_id.setter
    def base_asset_id(self, base_asset_id):
        """Sets the base_asset_id of this OrderBook.


        :param base_asset_id: The base_asset_id of this OrderBook.  # noqa: E501
        :type: str
        """

        self._base_asset_id = base_asset_id

    @property
    def created_at(self):
        """Gets the created_at of this OrderBook.  # noqa: E501


        :return: The created_at of this OrderBook.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this OrderBook.


        :param created_at: The created_at of this OrderBook.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def display_name(self):
        """Gets the display_name of this OrderBook.  # noqa: E501


        :return: The display_name of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this OrderBook.


        :param display_name: The display_name of this OrderBook.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def fee_factor(self):
        """Gets the fee_factor of this OrderBook.  # noqa: E501


        :return: The fee_factor of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._fee_factor

    @fee_factor.setter
    def fee_factor(self, fee_factor):
        """Sets the fee_factor of this OrderBook.


        :param fee_factor: The fee_factor of this OrderBook.  # noqa: E501
        :type: float
        """

        self._fee_factor = fee_factor

    @property
    def initial_assets_ratio(self):
        """Gets the initial_assets_ratio of this OrderBook.  # noqa: E501


        :return: The initial_assets_ratio of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._initial_assets_ratio

    @initial_assets_ratio.setter
    def initial_assets_ratio(self, initial_assets_ratio):
        """Sets the initial_assets_ratio of this OrderBook.


        :param initial_assets_ratio: The initial_assets_ratio of this OrderBook.  # noqa: E501
        :type: float
        """

        self._initial_assets_ratio = initial_assets_ratio

    @property
    def maturity_at(self):
        """Gets the maturity_at of this OrderBook.  # noqa: E501


        :return: The maturity_at of this OrderBook.  # noqa: E501
        :rtype: datetime
        """
        return self._maturity_at

    @maturity_at.setter
    def maturity_at(self, maturity_at):
        """Sets the maturity_at of this OrderBook.


        :param maturity_at: The maturity_at of this OrderBook.  # noqa: E501
        :type: datetime
        """

        self._maturity_at = maturity_at

    @property
    def price_display_multiplier(self):
        """Gets the price_display_multiplier of this OrderBook.  # noqa: E501


        :return: The price_display_multiplier of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._price_display_multiplier

    @price_display_multiplier.setter
    def price_display_multiplier(self, price_display_multiplier):
        """Sets the price_display_multiplier of this OrderBook.


        :param price_display_multiplier: The price_display_multiplier of this OrderBook.  # noqa: E501
        :type: float
        """

        self._price_display_multiplier = price_display_multiplier

    @property
    def quote_quantity(self):
        """Gets the quote_quantity of this OrderBook.  # noqa: E501


        :return: The quote_quantity of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._quote_quantity

    @quote_quantity.setter
    def quote_quantity(self, quote_quantity):
        """Sets the quote_quantity of this OrderBook.


        :param quote_quantity: The quote_quantity of this OrderBook.  # noqa: E501
        :type: float
        """

        self._quote_quantity = quote_quantity

    @property
    def quote_asset_id(self):
        """Gets the quote_asset_id of this OrderBook.  # noqa: E501


        :return: The quote_asset_id of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._quote_asset_id

    @quote_asset_id.setter
    def quote_asset_id(self, quote_asset_id):
        """Sets the quote_asset_id of this OrderBook.


        :param quote_asset_id: The quote_asset_id of this OrderBook.  # noqa: E501
        :type: str
        """

        self._quote_asset_id = quote_asset_id

    @property
    def shares_quantity(self):
        """Gets the shares_quantity of this OrderBook.  # noqa: E501


        :return: The shares_quantity of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._shares_quantity

    @shares_quantity.setter
    def shares_quantity(self, shares_quantity):
        """Sets the shares_quantity of this OrderBook.


        :param shares_quantity: The shares_quantity of this OrderBook.  # noqa: E501
        :type: float
        """

        self._shares_quantity = shares_quantity

    @property
    def status(self):
        """Gets the status of this OrderBook.  # noqa: E501


        :return: The status of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrderBook.


        :param status: The status of this OrderBook.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def tick_size(self):
        """Gets the tick_size of this OrderBook.  # noqa: E501


        :return: The tick_size of this OrderBook.  # noqa: E501
        :rtype: float
        """
        return self._tick_size

    @tick_size.setter
    def tick_size(self, tick_size):
        """Sets the tick_size of this OrderBook.


        :param tick_size: The tick_size of this OrderBook.  # noqa: E501
        :type: float
        """

        self._tick_size = tick_size

    @property
    def updated_at(self):
        """Gets the updated_at of this OrderBook.  # noqa: E501


        :return: The updated_at of this OrderBook.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this OrderBook.


        :param updated_at: The updated_at of this OrderBook.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def halted_at(self):
        """Gets the halted_at of this OrderBook.  # noqa: E501


        :return: The halted_at of this OrderBook.  # noqa: E501
        :rtype: datetime
        """
        return self._halted_at

    @halted_at.setter
    def halted_at(self, halted_at):
        """Sets the halted_at of this OrderBook.


        :param halted_at: The halted_at of this OrderBook.  # noqa: E501
        :type: datetime
        """

        self._halted_at = halted_at

    @property
    def terminated_at(self):
        """Gets the terminated_at of this OrderBook.  # noqa: E501


        :return: The terminated_at of this OrderBook.  # noqa: E501
        :rtype: datetime
        """
        return self._terminated_at

    @terminated_at.setter
    def terminated_at(self, terminated_at):
        """Sets the terminated_at of this OrderBook.


        :param terminated_at: The terminated_at of this OrderBook.  # noqa: E501
        :type: datetime
        """

        self._terminated_at = terminated_at

    @property
    def pool_updated_at(self):
        """Gets the pool_updated_at of this OrderBook.  # noqa: E501


        :return: The pool_updated_at of this OrderBook.  # noqa: E501
        :rtype: datetime
        """
        return self._pool_updated_at

    @pool_updated_at.setter
    def pool_updated_at(self, pool_updated_at):
        """Sets the pool_updated_at of this OrderBook.


        :param pool_updated_at: The pool_updated_at of this OrderBook.  # noqa: E501
        :type: datetime
        """

        self._pool_updated_at = pool_updated_at

    @property
    def pool_seq(self):
        """Gets the pool_seq of this OrderBook.  # noqa: E501


        :return: The pool_seq of this OrderBook.  # noqa: E501
        :rtype: int
        """
        return self._pool_seq

    @pool_seq.setter
    def pool_seq(self, pool_seq):
        """Sets the pool_seq of this OrderBook.


        :param pool_seq: The pool_seq of this OrderBook.  # noqa: E501
        :type: int
        """

        self._pool_seq = pool_seq

    @property
    def shares_asset_id(self):
        """Gets the shares_asset_id of this OrderBook.  # noqa: E501


        :return: The shares_asset_id of this OrderBook.  # noqa: E501
        :rtype: str
        """
        return self._shares_asset_id

    @shares_asset_id.setter
    def shares_asset_id(self, shares_asset_id):
        """Sets the shares_asset_id of this OrderBook.


        :param shares_asset_id: The shares_asset_id of this OrderBook.  # noqa: E501
        :type: str
        """

        self._shares_asset_id = shares_asset_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderBook, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderBook):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
