# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Order(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'order_book_id': 'str',
        'quantity': 'str',
        'kind': 'str',
        'price': 'str',
        'status': 'str',
        'user_id': 'str',
        'user_text': 'str',
        'order_modifiers': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'order_book_id': 'order_book_id',
        'quantity': 'quantity',
        'kind': 'kind',
        'price': 'price',
        'status': 'status',
        'user_id': 'user_id',
        'user_text': 'user_text',
        'order_modifiers': 'order_modifiers'
    }

    def __init__(self, id=None, order_book_id=None, quantity=None, kind=None, price=None, status=None, user_id=None, user_text=None, order_modifiers=None):  # noqa: E501
        """Order - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._order_book_id = None
        self._quantity = None
        self._kind = None
        self._price = None
        self._status = None
        self._user_id = None
        self._user_text = None
        self._order_modifiers = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if order_book_id is not None:
            self.order_book_id = order_book_id
        if quantity is not None:
            self.quantity = quantity
        if kind is not None:
            self.kind = kind
        if price is not None:
            self.price = price
        if status is not None:
            self.status = status
        if user_id is not None:
            self.user_id = user_id
        if user_text is not None:
            self.user_text = user_text
        if order_modifiers is not None:
            self.order_modifiers = order_modifiers

    @property
    def id(self):
        """Gets the id of this Order.  # noqa: E501


        :return: The id of this Order.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Order.


        :param id: The id of this Order.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def order_book_id(self):
        """Gets the order_book_id of this Order.  # noqa: E501


        :return: The order_book_id of this Order.  # noqa: E501
        :rtype: str
        """
        return self._order_book_id

    @order_book_id.setter
    def order_book_id(self, order_book_id):
        """Sets the order_book_id of this Order.


        :param order_book_id: The order_book_id of this Order.  # noqa: E501
        :type: str
        """

        self._order_book_id = order_book_id

    @property
    def quantity(self):
        """Gets the quantity of this Order.  # noqa: E501


        :return: The quantity of this Order.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this Order.


        :param quantity: The quantity of this Order.  # noqa: E501
        :type: str
        """

        self._quantity = quantity

    @property
    def kind(self):
        """Gets the kind of this Order.  # noqa: E501


        :return: The kind of this Order.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this Order.


        :param kind: The kind of this Order.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def price(self):
        """Gets the price of this Order.  # noqa: E501


        :return: The price of this Order.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this Order.


        :param price: The price of this Order.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def status(self):
        """Gets the status of this Order.  # noqa: E501


        :return: The status of this Order.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Order.


        :param status: The status of this Order.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def user_id(self):
        """Gets the user_id of this Order.  # noqa: E501


        :return: The user_id of this Order.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Order.


        :param user_id: The user_id of this Order.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def user_text(self):
        """Gets the user_text of this Order.  # noqa: E501


        :return: The user_text of this Order.  # noqa: E501
        :rtype: str
        """
        return self._user_text

    @user_text.setter
    def user_text(self, user_text):
        """Sets the user_text of this Order.


        :param user_text: The user_text of this Order.  # noqa: E501
        :type: str
        """

        self._user_text = user_text

    @property
    def order_modifiers(self):
        """Gets the order_modifiers of this Order.  # noqa: E501


        :return: The order_modifiers of this Order.  # noqa: E501
        :rtype: list[str]
        """
        return self._order_modifiers

    @order_modifiers.setter
    def order_modifiers(self, order_modifiers):
        """Sets the order_modifiers of this Order.


        :param order_modifiers: The order_modifiers of this Order.  # noqa: E501
        :type: list[str]
        """

        self._order_modifiers = order_modifiers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Order, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Order):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
