# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PLAsset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'symbol': 'str',
        'side': 'str',
        'avg_entry_price': 'str',
        'mark_price': 'str',
        'liquidation_price': 'str',
        'size': 'str',
        'margin': 'Margin',
        'unrealized_pl': 'str',
        'tp': 'str',
        'sl': 'str'
    }

    attribute_map = {
        'symbol': 'symbol',
        'side': 'side',
        'avg_entry_price': 'avg_entry_price',
        'mark_price': 'mark_price',
        'liquidation_price': 'liquidation_price',
        'size': 'size',
        'margin': 'margin',
        'unrealized_pl': 'unrealized_pl',
        'tp': 'tp',
        'sl': 'sl'
    }

    def __init__(self, symbol=None, side=None, avg_entry_price=None, mark_price=None, liquidation_price=None, size=None, margin=None, unrealized_pl=None, tp=None, sl=None):  # noqa: E501
        """PLAsset - a model defined in Swagger"""  # noqa: E501
        self._symbol = None
        self._side = None
        self._avg_entry_price = None
        self._mark_price = None
        self._liquidation_price = None
        self._size = None
        self._margin = None
        self._unrealized_pl = None
        self._tp = None
        self._sl = None
        self.discriminator = None
        if symbol is not None:
            self.symbol = symbol
        if side is not None:
            self.side = side
        if avg_entry_price is not None:
            self.avg_entry_price = avg_entry_price
        if mark_price is not None:
            self.mark_price = mark_price
        if liquidation_price is not None:
            self.liquidation_price = liquidation_price
        if size is not None:
            self.size = size
        if margin is not None:
            self.margin = margin
        if unrealized_pl is not None:
            self.unrealized_pl = unrealized_pl
        if tp is not None:
            self.tp = tp
        if sl is not None:
            self.sl = sl

    @property
    def symbol(self):
        """Gets the symbol of this PLAsset.  # noqa: E501

        The symbol of the asset  # noqa: E501

        :return: The symbol of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this PLAsset.

        The symbol of the asset  # noqa: E501

        :param symbol: The symbol of this PLAsset.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def side(self):
        """Gets the side of this PLAsset.  # noqa: E501

        The side of the position (LONG or SHORT)  # noqa: E501

        :return: The side of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this PLAsset.

        The side of the position (LONG or SHORT)  # noqa: E501

        :param side: The side of this PLAsset.  # noqa: E501
        :type: str
        """
        allowed_values = ["LONG", "SHORT"]  # noqa: E501
        if side not in allowed_values:
            raise ValueError(
                "Invalid value for `side` ({0}), must be one of {1}"  # noqa: E501
                .format(side, allowed_values)
            )

        self._side = side

    @property
    def avg_entry_price(self):
        """Gets the avg_entry_price of this PLAsset.  # noqa: E501

        The average entry price of the position  # noqa: E501

        :return: The avg_entry_price of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._avg_entry_price

    @avg_entry_price.setter
    def avg_entry_price(self, avg_entry_price):
        """Sets the avg_entry_price of this PLAsset.

        The average entry price of the position  # noqa: E501

        :param avg_entry_price: The avg_entry_price of this PLAsset.  # noqa: E501
        :type: str
        """

        self._avg_entry_price = avg_entry_price

    @property
    def mark_price(self):
        """Gets the mark_price of this PLAsset.  # noqa: E501

        The current mark price for the asset to calculate daily PL. This is usually the close price of the previous day  # noqa: E501

        :return: The mark_price of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._mark_price

    @mark_price.setter
    def mark_price(self, mark_price):
        """Sets the mark_price of this PLAsset.

        The current mark price for the asset to calculate daily PL. This is usually the close price of the previous day  # noqa: E501

        :param mark_price: The mark_price of this PLAsset.  # noqa: E501
        :type: str
        """

        self._mark_price = mark_price

    @property
    def liquidation_price(self):
        """Gets the liquidation_price of this PLAsset.  # noqa: E501

        The liquidation price of the position  # noqa: E501

        :return: The liquidation_price of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._liquidation_price

    @liquidation_price.setter
    def liquidation_price(self, liquidation_price):
        """Sets the liquidation_price of this PLAsset.

        The liquidation price of the position  # noqa: E501

        :param liquidation_price: The liquidation_price of this PLAsset.  # noqa: E501
        :type: str
        """

        self._liquidation_price = liquidation_price

    @property
    def size(self):
        """Gets the size of this PLAsset.  # noqa: E501

        The size of the position in units of the asset  # noqa: E501

        :return: The size of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this PLAsset.

        The size of the position in units of the asset  # noqa: E501

        :param size: The size of this PLAsset.  # noqa: E501
        :type: str
        """

        self._size = size

    @property
    def margin(self):
        """Gets the margin of this PLAsset.  # noqa: E501


        :return: The margin of this PLAsset.  # noqa: E501
        :rtype: Margin
        """
        return self._margin

    @margin.setter
    def margin(self, margin):
        """Sets the margin of this PLAsset.


        :param margin: The margin of this PLAsset.  # noqa: E501
        :type: Margin
        """

        self._margin = margin

    @property
    def unrealized_pl(self):
        """Gets the unrealized_pl of this PLAsset.  # noqa: E501

        The unrealized profit or loss of the position  # noqa: E501

        :return: The unrealized_pl of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._unrealized_pl

    @unrealized_pl.setter
    def unrealized_pl(self, unrealized_pl):
        """Sets the unrealized_pl of this PLAsset.

        The unrealized profit or loss of the position  # noqa: E501

        :param unrealized_pl: The unrealized_pl of this PLAsset.  # noqa: E501
        :type: str
        """

        self._unrealized_pl = unrealized_pl

    @property
    def tp(self):
        """Gets the tp of this PLAsset.  # noqa: E501

        The take profit price set for the position, if any  # noqa: E501

        :return: The tp of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._tp

    @tp.setter
    def tp(self, tp):
        """Sets the tp of this PLAsset.

        The take profit price set for the position, if any  # noqa: E501

        :param tp: The tp of this PLAsset.  # noqa: E501
        :type: str
        """

        self._tp = tp

    @property
    def sl(self):
        """Gets the sl of this PLAsset.  # noqa: E501

        The stop loss price set for the position, if any  # noqa: E501

        :return: The sl of this PLAsset.  # noqa: E501
        :rtype: str
        """
        return self._sl

    @sl.setter
    def sl(self, sl):
        """Sets the sl of this PLAsset.

        The stop loss price set for the position, if any  # noqa: E501

        :param sl: The sl of this PLAsset.  # noqa: E501
        :type: str
        """

        self._sl = sl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PLAsset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PLAsset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
