# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PLSummary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'leverage': 'dict',
        'account_equity': 'dict',
        'available': 'dict',
        'health': 'dict'
    }

    attribute_map = {
        'leverage': 'leverage',
        'account_equity': 'account_equity',
        'available': 'available',
        'health': 'health'
    }

    def __init__(self, leverage=None, account_equity=None, available=None, health=None):  # noqa: E501
        """PLSummary - a model defined in Swagger"""  # noqa: E501
        self._leverage = None
        self._account_equity = None
        self._available = None
        self._health = None
        self.discriminator = None
        if leverage is not None:
            self.leverage = leverage
        if account_equity is not None:
            self.account_equity = account_equity
        if available is not None:
            self.available = available
        if health is not None:
            self.health = health

    @property
    def leverage(self):
        """Gets the leverage of this PLSummary.  # noqa: E501

        The leverage used to obtain the position on the isolated account  # noqa: E501

        :return: The leverage of this PLSummary.  # noqa: E501
        :rtype: dict
        """
        return self._leverage

    @leverage.setter
    def leverage(self, leverage):
        """Sets the leverage of this PLSummary.

        The leverage used to obtain the position on the isolated account  # noqa: E501

        :param leverage: The leverage of this PLSummary.  # noqa: E501
        :type: dict
        """

        self._leverage = leverage

    @property
    def account_equity(self):
        """Gets the account_equity of this PLSummary.  # noqa: E501


        :return: The account_equity of this PLSummary.  # noqa: E501
        :rtype: dict
        """
        return self._account_equity

    @account_equity.setter
    def account_equity(self, account_equity):
        """Sets the account_equity of this PLSummary.


        :param account_equity: The account_equity of this PLSummary.  # noqa: E501
        :type: dict
        """

        self._account_equity = account_equity

    @property
    def available(self):
        """Gets the available of this PLSummary.  # noqa: E501


        :return: The available of this PLSummary.  # noqa: E501
        :rtype: dict
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this PLSummary.


        :param available: The available of this PLSummary.  # noqa: E501
        :type: dict
        """

        self._available = available

    @property
    def health(self):
        """Gets the health of this PLSummary.  # noqa: E501


        :return: The health of this PLSummary.  # noqa: E501
        :rtype: dict
        """
        return self._health

    @health.setter
    def health(self, health):
        """Sets the health of this PLSummary.


        :param health: The health of this PLSummary.  # noqa: E501
        :type: dict
        """

        self._health = health

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PLSummary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PLSummary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
