# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from dora_client.models.pn_l_ranking_response import PnLRankingResponse
from dora_client.models.pn_l_ranking_summary import PnLRankingSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PnLRankingResponses(BaseModel):
    """
    PnLRankingResponses
    """ # noqa: E501
    summary: PnLRankingSummary
    rankings: List[PnLRankingResponse]
    __properties: ClassVar[List[str]] = ["summary", "rankings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PnLRankingResponses from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rankings (list)
        _items = []
        if self.rankings:
            for _item_rankings in self.rankings:
                if _item_rankings:
                    _items.append(_item_rankings.to_dict())
            _dict['rankings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PnLRankingResponses from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "summary": PnLRankingSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "rankings": [PnLRankingResponse.from_dict(_item) for _item in obj["rankings"]] if obj.get("rankings") is not None else None
        })
        return _obj


