# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PoolPrice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pool_id': 'str',
        'price': 'str',
        'timestamp': 'datetime'
    }

    attribute_map = {
        'pool_id': 'pool_id',
        'price': 'price',
        'timestamp': 'timestamp'
    }

    def __init__(self, pool_id=None, price=None, timestamp=None):  # noqa: E501
        """PoolPrice - a model defined in Swagger"""  # noqa: E501
        self._pool_id = None
        self._price = None
        self._timestamp = None
        self.discriminator = None
        if pool_id is not None:
            self.pool_id = pool_id
        if price is not None:
            self.price = price
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def pool_id(self):
        """Gets the pool_id of this PoolPrice.  # noqa: E501


        :return: The pool_id of this PoolPrice.  # noqa: E501
        :rtype: str
        """
        return self._pool_id

    @pool_id.setter
    def pool_id(self, pool_id):
        """Sets the pool_id of this PoolPrice.


        :param pool_id: The pool_id of this PoolPrice.  # noqa: E501
        :type: str
        """

        self._pool_id = pool_id

    @property
    def price(self):
        """Gets the price of this PoolPrice.  # noqa: E501


        :return: The price of this PoolPrice.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PoolPrice.


        :param price: The price of this PoolPrice.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def timestamp(self):
        """Gets the timestamp of this PoolPrice.  # noqa: E501


        :return: The timestamp of this PoolPrice.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this PoolPrice.


        :param timestamp: The timestamp of this PoolPrice.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoolPrice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoolPrice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
