# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from dora_client.models.position import Position
from dora_client.models.transformed_assets import TransformedAssets
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Portfolio(BaseModel):
    """
    Portfolio
    """ # noqa: E501
    user_id: Optional[UUID] = None
    position: Optional[Dict[str, Dict[str, Position]]] = None
    net_stablecoin_equivalence: Optional[TransformedAssets] = None
    __properties: ClassVar[List[str]] = ["user_id", "position", "net_stablecoin_equivalence"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Portfolio from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in position (dict of dict)
        _field_dict_of_dict = {}
        if self.position:
            for _key_position, _value_position in self.position.items():
                if _value_position is not None:
                    _field_dict_of_dict[_key_position] = {
                        _key: _value.to_dict() for _key, _value in _value_position.items()
                    }
            _dict['position'] = _field_dict_of_dict
        # override the default output from pydantic by calling `to_dict()` of net_stablecoin_equivalence
        if self.net_stablecoin_equivalence:
            _dict['net_stablecoin_equivalence'] = self.net_stablecoin_equivalence.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Portfolio from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "position": dict(
                (_k, dict(
                    (_ik, Position.from_dict(_iv))
                        for _ik, _iv in _v.items()
                    )
                    if _v is not None
                    else None
                )
                for _k, _v in obj["position"].items()
            )
            if obj.get("position") is not None
            else None,
            "net_stablecoin_equivalence": TransformedAssets.from_dict(obj["net_stablecoin_equivalence"]) if obj.get("net_stablecoin_equivalence") is not None else None
        })
        return _obj


