# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PositionAccount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position_id': 'str',
        'position_name': 'str',
        'is_global': 'bool'
    }

    attribute_map = {
        'position_id': 'position_id',
        'position_name': 'position_name',
        'is_global': 'is_global'
    }

    def __init__(self, position_id=None, position_name=None, is_global=None):  # noqa: E501
        """PositionAccount - a model defined in Swagger"""  # noqa: E501
        self._position_id = None
        self._position_name = None
        self._is_global = None
        self.discriminator = None
        if position_id is not None:
            self.position_id = position_id
        if position_name is not None:
            self.position_name = position_name
        if is_global is not None:
            self.is_global = is_global

    @property
    def position_id(self):
        """Gets the position_id of this PositionAccount.  # noqa: E501

        The ID of the position account  # noqa: E501

        :return: The position_id of this PositionAccount.  # noqa: E501
        :rtype: str
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this PositionAccount.

        The ID of the position account  # noqa: E501

        :param position_id: The position_id of this PositionAccount.  # noqa: E501
        :type: str
        """

        self._position_id = position_id

    @property
    def position_name(self):
        """Gets the position_name of this PositionAccount.  # noqa: E501

        The name of the position account  # noqa: E501

        :return: The position_name of this PositionAccount.  # noqa: E501
        :rtype: str
        """
        return self._position_name

    @position_name.setter
    def position_name(self, position_name):
        """Sets the position_name of this PositionAccount.

        The name of the position account  # noqa: E501

        :param position_name: The position_name of this PositionAccount.  # noqa: E501
        :type: str
        """

        self._position_name = position_name

    @property
    def is_global(self):
        """Gets the is_global of this PositionAccount.  # noqa: E501

        Whether the position account is the global or an isolated account  # noqa: E501

        :return: The is_global of this PositionAccount.  # noqa: E501
        :rtype: bool
        """
        return self._is_global

    @is_global.setter
    def is_global(self, is_global):
        """Sets the is_global of this PositionAccount.

        Whether the position account is the global or an isolated account  # noqa: E501

        :param is_global: The is_global of this PositionAccount.  # noqa: E501
        :type: bool
        """

        self._is_global = is_global

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PositionAccount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PositionAccount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
