# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from dora_client.models.promo_claim_state import PromoClaimState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PromoClaimResponseEnvelopeAllOfData(BaseModel):
    """
    PromoClaimResponseEnvelopeAllOfData
    """ # noqa: E501
    state: PromoClaimState
    email: Optional[StrictStr] = None
    campaign_name: Optional[StrictStr] = None
    promo_credit: Optional[StrictStr] = None
    min_reward_amount: Optional[StrictStr] = None
    max_reward_amount: Optional[StrictStr] = None
    target_equity: Optional[StrictStr] = None
    expires_at: Optional[datetime] = None
    source_name: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["state", "email", "campaign_name", "promo_credit", "min_reward_amount", "max_reward_amount", "target_equity", "expires_at", "source_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromoClaimResponseEnvelopeAllOfData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromoClaimResponseEnvelopeAllOfData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "state": obj.get("state"),
            "email": obj.get("email"),
            "campaign_name": obj.get("campaign_name"),
            "promo_credit": obj.get("promo_credit"),
            "min_reward_amount": obj.get("min_reward_amount"),
            "max_reward_amount": obj.get("max_reward_amount"),
            "target_equity": obj.get("target_equity"),
            "expires_at": obj.get("expires_at"),
            "source_name": obj.get("source_name")
        })
        return _obj


