# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from dora_client.models.stream_entry import StreamEntry  # noqa: F401,E501

class StreamOrderUpdatesEntry(StreamEntry):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'val': 'Order'
    }
    if hasattr(StreamEntry, "swagger_types"):
        swagger_types.update(StreamEntry.swagger_types)

    attribute_map = {
        'val': 'Val'
    }
    if hasattr(StreamEntry, "attribute_map"):
        attribute_map.update(StreamEntry.attribute_map)

    def __init__(self, val=None, *args, **kwargs):  # noqa: E501
        """StreamOrderUpdatesEntry - a model defined in Swagger"""  # noqa: E501
        self._val = None
        self.discriminator = None
        if val is not None:
            self.val = val
        StreamEntry.__init__(self, *args, **kwargs)

    @property
    def val(self):
        """Gets the val of this StreamOrderUpdatesEntry.  # noqa: E501


        :return: The val of this StreamOrderUpdatesEntry.  # noqa: E501
        :rtype: Order
        """
        return self._val

    @val.setter
    def val(self, val):
        """Sets the val of this StreamOrderUpdatesEntry.


        :param val: The val of this StreamOrderUpdatesEntry.  # noqa: E501
        :type: Order
        """

        self._val = val

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StreamOrderUpdatesEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StreamOrderUpdatesEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
