# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from dora_client.models.trading_challenge_status import TradingChallengeStatus
from dora_client.models.trading_challenge_type import TradingChallengeType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TradingChallenge(BaseModel):
    """
    TradingChallenge
    """ # noqa: E501
    id: UUID
    name: Optional[StrictStr] = Field(default=None, description="Trading challenge name")
    tenant_id: StrictStr
    type: TradingChallengeType
    status: TradingChallengeStatus
    max_users: StrictInt
    start_at: datetime
    end_at: datetime
    initial_user_balance: StrictStr
    gold_prize_quantity: StrictStr
    silver_prize_quantity: StrictStr
    bronze_prize_quantity: StrictStr
    pnl_condition: StrictStr
    total_volume_condition: StrictStr
    avg_daily_volume_condition: StrictStr
    minimum_equity_percentage_condition: StrictInt
    created_at: datetime
    last_processed_at: Optional[datetime] = None
    users: Optional[List[UUID]] = None
    users_count: StrictInt
    __properties: ClassVar[List[str]] = ["id", "name", "tenant_id", "type", "status", "max_users", "start_at", "end_at", "initial_user_balance", "gold_prize_quantity", "silver_prize_quantity", "bronze_prize_quantity", "pnl_condition", "total_volume_condition", "avg_daily_volume_condition", "minimum_equity_percentage_condition", "created_at", "last_processed_at", "users", "users_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradingChallenge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradingChallenge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "tenant_id": obj.get("tenant_id"),
            "type": obj.get("type"),
            "status": obj.get("status"),
            "max_users": obj.get("max_users"),
            "start_at": obj.get("start_at"),
            "end_at": obj.get("end_at"),
            "initial_user_balance": obj.get("initial_user_balance"),
            "gold_prize_quantity": obj.get("gold_prize_quantity"),
            "silver_prize_quantity": obj.get("silver_prize_quantity"),
            "bronze_prize_quantity": obj.get("bronze_prize_quantity"),
            "pnl_condition": obj.get("pnl_condition"),
            "total_volume_condition": obj.get("total_volume_condition"),
            "avg_daily_volume_condition": obj.get("avg_daily_volume_condition"),
            "minimum_equity_percentage_condition": obj.get("minimum_equity_percentage_condition"),
            "created_at": obj.get("created_at"),
            "last_processed_at": obj.get("last_processed_at"),
            "users": obj.get("users"),
            "users_count": obj.get("users_count")
        })
        return _obj


