# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TradingChallengeDailySnapshot(BaseModel):
    """
    TradingChallengeDailySnapshot
    """ # noqa: E501
    trading_challenge_id: Optional[UUID] = None
    user_id: Optional[UUID] = None
    user_name: Optional[StrictStr] = None
    trading_date: Optional[date] = None
    daily_volume: Optional[StrictStr] = None
    daily_pnl: Optional[StrictStr] = None
    daily_trades: Optional[StrictInt] = None
    volume_compliant: Optional[StrictBool] = None
    eod_equity: Optional[StrictStr] = None
    active_day: Optional[StrictBool] = None
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["trading_challenge_id", "user_id", "user_name", "trading_date", "daily_volume", "daily_pnl", "daily_trades", "volume_compliant", "eod_equity", "active_day", "created_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TradingChallengeDailySnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TradingChallengeDailySnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trading_challenge_id": obj.get("trading_challenge_id"),
            "user_id": obj.get("user_id"),
            "user_name": obj.get("user_name"),
            "trading_date": obj.get("trading_date"),
            "daily_volume": obj.get("daily_volume"),
            "daily_pnl": obj.get("daily_pnl"),
            "daily_trades": obj.get("daily_trades"),
            "volume_compliant": obj.get("volume_compliant"),
            "eod_equity": obj.get("eod_equity"),
            "active_day": obj.get("active_day"),
            "created_at": obj.get("created_at")
        })
        return _obj


