# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TransformedAssets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gained': 'dict',
        'lost': 'dict'
    }

    attribute_map = {
        'gained': 'gained',
        'lost': 'lost'
    }

    def __init__(self, gained=None, lost=None):  # noqa: E501
        """TransformedAssets - a model defined in Swagger"""  # noqa: E501
        self._gained = None
        self._lost = None
        self.discriminator = None
        if gained is not None:
            self.gained = gained
        if lost is not None:
            self.lost = lost

    @property
    def gained(self):
        """Gets the gained of this TransformedAssets.  # noqa: E501

        Assets that have been gained by stablecoin equivalence transformations. They cannot be withdrawn from the platform until converted back to the original asset.  # noqa: E501

        :return: The gained of this TransformedAssets.  # noqa: E501
        :rtype: dict
        """
        return self._gained

    @gained.setter
    def gained(self, gained):
        """Sets the gained of this TransformedAssets.

        Assets that have been gained by stablecoin equivalence transformations. They cannot be withdrawn from the platform until converted back to the original asset.  # noqa: E501

        :param gained: The gained of this TransformedAssets.  # noqa: E501
        :type: dict
        """

        self._gained = gained

    @property
    def lost(self):
        """Gets the lost of this TransformedAssets.  # noqa: E501

        Assets that have been lost by stablecoin equivalence transformations. They can be recovered by converting back any assets gained by stablecoin equivalence transformations.  # noqa: E501

        :return: The lost of this TransformedAssets.  # noqa: E501
        :rtype: dict
        """
        return self._lost

    @lost.setter
    def lost(self, lost):
        """Sets the lost of this TransformedAssets.

        Assets that have been lost by stablecoin equivalence transformations. They can be recovered by converting back any assets gained by stablecoin equivalence transformations.  # noqa: E501

        :param lost: The lost of this TransformedAssets.  # noqa: E501
        :type: dict
        """

        self._lost = lost

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransformedAssets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransformedAssets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
