# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UnitedPosition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'global_position_id': 'str',
        'transaction_ids': 'list[str]'
    }

    attribute_map = {
        'global_position_id': 'global_position_id',
        'transaction_ids': 'transaction_ids'
    }

    def __init__(self, global_position_id=None, transaction_ids=None):  # noqa: E501
        """UnitedPosition - a model defined in Swagger"""  # noqa: E501
        self._global_position_id = None
        self._transaction_ids = None
        self.discriminator = None
        if global_position_id is not None:
            self.global_position_id = global_position_id
        if transaction_ids is not None:
            self.transaction_ids = transaction_ids

    @property
    def global_position_id(self):
        """Gets the global_position_id of this UnitedPosition.  # noqa: E501


        :return: The global_position_id of this UnitedPosition.  # noqa: E501
        :rtype: str
        """
        return self._global_position_id

    @global_position_id.setter
    def global_position_id(self, global_position_id):
        """Sets the global_position_id of this UnitedPosition.


        :param global_position_id: The global_position_id of this UnitedPosition.  # noqa: E501
        :type: str
        """

        self._global_position_id = global_position_id

    @property
    def transaction_ids(self):
        """Gets the transaction_ids of this UnitedPosition.  # noqa: E501


        :return: The transaction_ids of this UnitedPosition.  # noqa: E501
        :rtype: list[str]
        """
        return self._transaction_ids

    @transaction_ids.setter
    def transaction_ids(self, transaction_ids):
        """Sets the transaction_ids of this UnitedPosition.


        :param transaction_ids: The transaction_ids of this UnitedPosition.  # noqa: E501
        :type: list[str]
        """

        self._transaction_ids = transaction_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnitedPosition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnitedPosition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
