# coding: utf-8

"""
    DORA

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from dora_client.models.update_affiliate_program_request_description import UpdateAffiliateProgramRequestDescription
from dora_client.models.update_affiliate_program_request_is_active import UpdateAffiliateProgramRequestIsActive
from dora_client.models.update_affiliate_program_request_name import UpdateAffiliateProgramRequestName
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateAffiliateProgramRequest(BaseModel):
    """
    UpdateAffiliateProgramRequest
    """ # noqa: E501
    name: Optional[UpdateAffiliateProgramRequestName] = None
    description: Optional[UpdateAffiliateProgramRequestDescription] = None
    is_active: Optional[UpdateAffiliateProgramRequestIsActive] = None
    __properties: ClassVar[List[str]] = ["name", "description", "is_active"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAffiliateProgramRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of name
        if self.name:
            _dict['name'] = self.name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of description
        if self.description:
            _dict['description'] = self.description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of is_active
        if self.is_active:
            _dict['is_active'] = self.is_active.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAffiliateProgramRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": UpdateAffiliateProgramRequestName.from_dict(obj["name"]) if obj.get("name") is not None else None,
            "description": UpdateAffiliateProgramRequestDescription.from_dict(obj["description"]) if obj.get("description") is not None else None,
            "is_active": UpdateAffiliateProgramRequestIsActive.from_dict(obj["is_active"]) if obj.get("is_active") is not None else None
        })
        return _obj


