# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateAssetReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'collateral_weight': 'float',
        'decimals': 'int',
        'description': 'str',
        'name': 'str',
        'maturity_id': 'str',
        'max_supply': 'int',
        'max_utilization': 'int',
        'liquidation_threshold': 'float',
        'symbol': 'str',
        'kind': 'str',
        '_yield': 'float',
        'capabilities': 'CreateAssetReqCapabilities',
        'bond': 'UpdateBondReq'
    }

    attribute_map = {
        'collateral_weight': 'collateral_weight',
        'decimals': 'decimals',
        'description': 'description',
        'name': 'name',
        'maturity_id': 'maturity_id',
        'max_supply': 'max_supply',
        'max_utilization': 'max_utilization',
        'liquidation_threshold': 'liquidation_threshold',
        'symbol': 'symbol',
        'kind': 'kind',
        '_yield': 'yield',
        'capabilities': 'capabilities',
        'bond': 'bond'
    }

    def __init__(self, collateral_weight=None, decimals=None, description=None, name=None, maturity_id=None, max_supply=None, max_utilization=None, liquidation_threshold=None, symbol=None, kind=None, _yield=None, capabilities=None, bond=None):  # noqa: E501
        """UpdateAssetReq - a model defined in Swagger"""  # noqa: E501
        self._collateral_weight = None
        self._decimals = None
        self._description = None
        self._name = None
        self._maturity_id = None
        self._max_supply = None
        self._max_utilization = None
        self._liquidation_threshold = None
        self._symbol = None
        self._kind = None
        self.__yield = None
        self._capabilities = None
        self._bond = None
        self.discriminator = None
        if collateral_weight is not None:
            self.collateral_weight = collateral_weight
        if decimals is not None:
            self.decimals = decimals
        if description is not None:
            self.description = description
        if name is not None:
            self.name = name
        if maturity_id is not None:
            self.maturity_id = maturity_id
        if max_supply is not None:
            self.max_supply = max_supply
        if max_utilization is not None:
            self.max_utilization = max_utilization
        if liquidation_threshold is not None:
            self.liquidation_threshold = liquidation_threshold
        if symbol is not None:
            self.symbol = symbol
        if kind is not None:
            self.kind = kind
        if _yield is not None:
            self._yield = _yield
        if capabilities is not None:
            self.capabilities = capabilities
        if bond is not None:
            self.bond = bond

    @property
    def collateral_weight(self):
        """Gets the collateral_weight of this UpdateAssetReq.  # noqa: E501


        :return: The collateral_weight of this UpdateAssetReq.  # noqa: E501
        :rtype: float
        """
        return self._collateral_weight

    @collateral_weight.setter
    def collateral_weight(self, collateral_weight):
        """Sets the collateral_weight of this UpdateAssetReq.


        :param collateral_weight: The collateral_weight of this UpdateAssetReq.  # noqa: E501
        :type: float
        """

        self._collateral_weight = collateral_weight

    @property
    def decimals(self):
        """Gets the decimals of this UpdateAssetReq.  # noqa: E501


        :return: The decimals of this UpdateAssetReq.  # noqa: E501
        :rtype: int
        """
        return self._decimals

    @decimals.setter
    def decimals(self, decimals):
        """Sets the decimals of this UpdateAssetReq.


        :param decimals: The decimals of this UpdateAssetReq.  # noqa: E501
        :type: int
        """

        self._decimals = decimals

    @property
    def description(self):
        """Gets the description of this UpdateAssetReq.  # noqa: E501


        :return: The description of this UpdateAssetReq.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UpdateAssetReq.


        :param description: The description of this UpdateAssetReq.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this UpdateAssetReq.  # noqa: E501


        :return: The name of this UpdateAssetReq.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateAssetReq.


        :param name: The name of this UpdateAssetReq.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def maturity_id(self):
        """Gets the maturity_id of this UpdateAssetReq.  # noqa: E501


        :return: The maturity_id of this UpdateAssetReq.  # noqa: E501
        :rtype: str
        """
        return self._maturity_id

    @maturity_id.setter
    def maturity_id(self, maturity_id):
        """Sets the maturity_id of this UpdateAssetReq.


        :param maturity_id: The maturity_id of this UpdateAssetReq.  # noqa: E501
        :type: str
        """

        self._maturity_id = maturity_id

    @property
    def max_supply(self):
        """Gets the max_supply of this UpdateAssetReq.  # noqa: E501


        :return: The max_supply of this UpdateAssetReq.  # noqa: E501
        :rtype: int
        """
        return self._max_supply

    @max_supply.setter
    def max_supply(self, max_supply):
        """Sets the max_supply of this UpdateAssetReq.


        :param max_supply: The max_supply of this UpdateAssetReq.  # noqa: E501
        :type: int
        """

        self._max_supply = max_supply

    @property
    def max_utilization(self):
        """Gets the max_utilization of this UpdateAssetReq.  # noqa: E501


        :return: The max_utilization of this UpdateAssetReq.  # noqa: E501
        :rtype: int
        """
        return self._max_utilization

    @max_utilization.setter
    def max_utilization(self, max_utilization):
        """Sets the max_utilization of this UpdateAssetReq.


        :param max_utilization: The max_utilization of this UpdateAssetReq.  # noqa: E501
        :type: int
        """

        self._max_utilization = max_utilization

    @property
    def liquidation_threshold(self):
        """Gets the liquidation_threshold of this UpdateAssetReq.  # noqa: E501


        :return: The liquidation_threshold of this UpdateAssetReq.  # noqa: E501
        :rtype: float
        """
        return self._liquidation_threshold

    @liquidation_threshold.setter
    def liquidation_threshold(self, liquidation_threshold):
        """Sets the liquidation_threshold of this UpdateAssetReq.


        :param liquidation_threshold: The liquidation_threshold of this UpdateAssetReq.  # noqa: E501
        :type: float
        """

        self._liquidation_threshold = liquidation_threshold

    @property
    def symbol(self):
        """Gets the symbol of this UpdateAssetReq.  # noqa: E501


        :return: The symbol of this UpdateAssetReq.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this UpdateAssetReq.


        :param symbol: The symbol of this UpdateAssetReq.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def kind(self):
        """Gets the kind of this UpdateAssetReq.  # noqa: E501


        :return: The kind of this UpdateAssetReq.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this UpdateAssetReq.


        :param kind: The kind of this UpdateAssetReq.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def _yield(self):
        """Gets the _yield of this UpdateAssetReq.  # noqa: E501


        :return: The _yield of this UpdateAssetReq.  # noqa: E501
        :rtype: float
        """
        return self.__yield

    @_yield.setter
    def _yield(self, _yield):
        """Sets the _yield of this UpdateAssetReq.


        :param _yield: The _yield of this UpdateAssetReq.  # noqa: E501
        :type: float
        """

        self.__yield = _yield

    @property
    def capabilities(self):
        """Gets the capabilities of this UpdateAssetReq.  # noqa: E501


        :return: The capabilities of this UpdateAssetReq.  # noqa: E501
        :rtype: CreateAssetReqCapabilities
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities):
        """Sets the capabilities of this UpdateAssetReq.


        :param capabilities: The capabilities of this UpdateAssetReq.  # noqa: E501
        :type: CreateAssetReqCapabilities
        """

        self._capabilities = capabilities

    @property
    def bond(self):
        """Gets the bond of this UpdateAssetReq.  # noqa: E501


        :return: The bond of this UpdateAssetReq.  # noqa: E501
        :rtype: UpdateBondReq
        """
        return self._bond

    @bond.setter
    def bond(self, bond):
        """Sets the bond of this UpdateAssetReq.


        :param bond: The bond of this UpdateAssetReq.  # noqa: E501
        :type: UpdateBondReq
        """

        self._bond = bond

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateAssetReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateAssetReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
