# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserCouponPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'dict',
        'position_id': 'dict',
        'asset_id': 'dict',
        'coupon_payment_id': 'dict',
        'seq': 'dict',
        'pending': 'dict',
        'completed': 'dict',
        'started_at': 'dict',
        'ended_at': 'dict'
    }

    attribute_map = {
        'user_id': 'user_id',
        'position_id': 'position_id',
        'asset_id': 'asset_id',
        'coupon_payment_id': 'coupon_payment_id',
        'seq': 'seq',
        'pending': 'pending',
        'completed': 'completed',
        'started_at': 'started_at',
        'ended_at': 'ended_at'
    }

    def __init__(self, user_id=None, position_id=None, asset_id=None, coupon_payment_id=None, seq=None, pending=None, completed=None, started_at=None, ended_at=None):  # noqa: E501
        """UserCouponPayment - a model defined in Swagger"""  # noqa: E501
        self._user_id = None
        self._position_id = None
        self._asset_id = None
        self._coupon_payment_id = None
        self._seq = None
        self._pending = None
        self._completed = None
        self._started_at = None
        self._ended_at = None
        self.discriminator = None
        if user_id is not None:
            self.user_id = user_id
        if position_id is not None:
            self.position_id = position_id
        if asset_id is not None:
            self.asset_id = asset_id
        if coupon_payment_id is not None:
            self.coupon_payment_id = coupon_payment_id
        if seq is not None:
            self.seq = seq
        if pending is not None:
            self.pending = pending
        if completed is not None:
            self.completed = completed
        if started_at is not None:
            self.started_at = started_at
        if ended_at is not None:
            self.ended_at = ended_at

    @property
    def user_id(self):
        """Gets the user_id of this UserCouponPayment.  # noqa: E501


        :return: The user_id of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserCouponPayment.


        :param user_id: The user_id of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._user_id = user_id

    @property
    def position_id(self):
        """Gets the position_id of this UserCouponPayment.  # noqa: E501


        :return: The position_id of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this UserCouponPayment.


        :param position_id: The position_id of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._position_id = position_id

    @property
    def asset_id(self):
        """Gets the asset_id of this UserCouponPayment.  # noqa: E501


        :return: The asset_id of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this UserCouponPayment.


        :param asset_id: The asset_id of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._asset_id = asset_id

    @property
    def coupon_payment_id(self):
        """Gets the coupon_payment_id of this UserCouponPayment.  # noqa: E501


        :return: The coupon_payment_id of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._coupon_payment_id

    @coupon_payment_id.setter
    def coupon_payment_id(self, coupon_payment_id):
        """Sets the coupon_payment_id of this UserCouponPayment.


        :param coupon_payment_id: The coupon_payment_id of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._coupon_payment_id = coupon_payment_id

    @property
    def seq(self):
        """Gets the seq of this UserCouponPayment.  # noqa: E501


        :return: The seq of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._seq

    @seq.setter
    def seq(self, seq):
        """Sets the seq of this UserCouponPayment.


        :param seq: The seq of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._seq = seq

    @property
    def pending(self):
        """Gets the pending of this UserCouponPayment.  # noqa: E501


        :return: The pending of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._pending

    @pending.setter
    def pending(self, pending):
        """Sets the pending of this UserCouponPayment.


        :param pending: The pending of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._pending = pending

    @property
    def completed(self):
        """Gets the completed of this UserCouponPayment.  # noqa: E501


        :return: The completed of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this UserCouponPayment.


        :param completed: The completed of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._completed = completed

    @property
    def started_at(self):
        """Gets the started_at of this UserCouponPayment.  # noqa: E501


        :return: The started_at of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this UserCouponPayment.


        :param started_at: The started_at of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._started_at = started_at

    @property
    def ended_at(self):
        """Gets the ended_at of this UserCouponPayment.  # noqa: E501


        :return: The ended_at of this UserCouponPayment.  # noqa: E501
        :rtype: dict
        """
        return self._ended_at

    @ended_at.setter
    def ended_at(self, ended_at):
        """Sets the ended_at of this UserCouponPayment.


        :param ended_at: The ended_at of this UserCouponPayment.  # noqa: E501
        :type: dict
        """

        self._ended_at = ended_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserCouponPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserCouponPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
