# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserInterestResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'available': 'dict(str, int)',
        'value': 'dict(str, str)'
    }

    attribute_map = {
        'available': 'available',
        'value': 'value'
    }

    def __init__(self, available=None, value=None):  # noqa: E501
        """UserInterestResponse - a model defined in Swagger"""  # noqa: E501
        self._available = None
        self._value = None
        self.discriminator = None
        if available is not None:
            self.available = available
        if value is not None:
            self.value = value

    @property
    def available(self):
        """Gets the available of this UserInterestResponse.  # noqa: E501


        :return: The available of this UserInterestResponse.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this UserInterestResponse.


        :param available: The available of this UserInterestResponse.  # noqa: E501
        :type: dict(str, int)
        """

        self._available = available

    @property
    def value(self):
        """Gets the value of this UserInterestResponse.  # noqa: E501


        :return: The value of this UserInterestResponse.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this UserInterestResponse.


        :param value: The value of this UserInterestResponse.  # noqa: E501
        :type: dict(str, str)
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserInterestResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserInterestResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
