# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ValidateSubmitOrderRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantity': 'str',
        'tick': 'str',
        'kind': 'OrderKind',
        'side': 'Side',
        'price': 'str',
        'good_till_date': 'datetime',
        'inverse_leverage': 'str',
        'user_balance': 'str'
    }

    attribute_map = {
        'quantity': 'quantity',
        'tick': 'tick',
        'kind': 'kind',
        'side': 'side',
        'price': 'price',
        'good_till_date': 'good_till_date',
        'inverse_leverage': 'inverse_leverage',
        'user_balance': 'user_balance'
    }

    def __init__(self, quantity=None, tick=None, kind=None, side=None, price=None, good_till_date=None, inverse_leverage=None, user_balance=None):  # noqa: E501
        """ValidateSubmitOrderRequest - a model defined in Swagger"""  # noqa: E501
        self._quantity = None
        self._tick = None
        self._kind = None
        self._side = None
        self._price = None
        self._good_till_date = None
        self._inverse_leverage = None
        self._user_balance = None
        self.discriminator = None
        self.quantity = quantity
        self.tick = tick
        self.kind = kind
        if side is not None:
            self.side = side
        self.price = price
        if good_till_date is not None:
            self.good_till_date = good_till_date
        self.inverse_leverage = inverse_leverage
        self.user_balance = user_balance

    @property
    def quantity(self):
        """Gets the quantity of this ValidateSubmitOrderRequest.  # noqa: E501


        :return: The quantity of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this ValidateSubmitOrderRequest.


        :param quantity: The quantity of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: str
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def tick(self):
        """Gets the tick of this ValidateSubmitOrderRequest.  # noqa: E501

        Minimum tradable increment for the selected order book  # noqa: E501

        :return: The tick of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._tick

    @tick.setter
    def tick(self, tick):
        """Sets the tick of this ValidateSubmitOrderRequest.

        Minimum tradable increment for the selected order book  # noqa: E501

        :param tick: The tick of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: str
        """
        if tick is None:
            raise ValueError("Invalid value for `tick`, must not be `None`")  # noqa: E501

        self._tick = tick

    @property
    def kind(self):
        """Gets the kind of this ValidateSubmitOrderRequest.  # noqa: E501


        :return: The kind of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: OrderKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ValidateSubmitOrderRequest.


        :param kind: The kind of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: OrderKind
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def side(self):
        """Gets the side of this ValidateSubmitOrderRequest.  # noqa: E501


        :return: The side of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: Side
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this ValidateSubmitOrderRequest.


        :param side: The side of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: Side
        """

        self._side = side

    @property
    def price(self):
        """Gets the price of this ValidateSubmitOrderRequest.  # noqa: E501

        If kind is LIMIT, must be > 0; if MARKET it must be 0 or omitted  # noqa: E501

        :return: The price of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this ValidateSubmitOrderRequest.

        If kind is LIMIT, must be > 0; if MARKET it must be 0 or omitted  # noqa: E501

        :param price: The price of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: str
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def good_till_date(self):
        """Gets the good_till_date of this ValidateSubmitOrderRequest.  # noqa: E501


        :return: The good_till_date of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._good_till_date

    @good_till_date.setter
    def good_till_date(self, good_till_date):
        """Sets the good_till_date of this ValidateSubmitOrderRequest.


        :param good_till_date: The good_till_date of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: datetime
        """

        self._good_till_date = good_till_date

    @property
    def inverse_leverage(self):
        """Gets the inverse_leverage of this ValidateSubmitOrderRequest.  # noqa: E501


        :return: The inverse_leverage of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._inverse_leverage

    @inverse_leverage.setter
    def inverse_leverage(self, inverse_leverage):
        """Sets the inverse_leverage of this ValidateSubmitOrderRequest.


        :param inverse_leverage: The inverse_leverage of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: str
        """
        if inverse_leverage is None:
            raise ValueError("Invalid value for `inverse_leverage`, must not be `None`")  # noqa: E501

        self._inverse_leverage = inverse_leverage

    @property
    def user_balance(self):
        """Gets the user_balance of this ValidateSubmitOrderRequest.  # noqa: E501

        User balance used to ensure they can afford the requested quantity  # noqa: E501

        :return: The user_balance of this ValidateSubmitOrderRequest.  # noqa: E501
        :rtype: str
        """
        return self._user_balance

    @user_balance.setter
    def user_balance(self, user_balance):
        """Sets the user_balance of this ValidateSubmitOrderRequest.

        User balance used to ensure they can afford the requested quantity  # noqa: E501

        :param user_balance: The user_balance of this ValidateSubmitOrderRequest.  # noqa: E501
        :type: str
        """
        if user_balance is None:
            raise ValueError("Invalid value for `user_balance`, must not be `None`")  # noqa: E501

        self._user_balance = user_balance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidateSubmitOrderRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidateSubmitOrderRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
