# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ValidateSubmitOrderRequestPositionAssets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset_id': 'str',
        'kind': 'AssetKind',
        'borrowed': 'str',
        'impending_borrows': 'str',
        'available': 'str',
        'locked': 'str'
    }

    attribute_map = {
        'asset_id': 'asset_id',
        'kind': 'kind',
        'borrowed': 'borrowed',
        'impending_borrows': 'impending_borrows',
        'available': 'available',
        'locked': 'locked'
    }

    def __init__(self, asset_id=None, kind=None, borrowed=None, impending_borrows=None, available=None, locked=None):  # noqa: E501
        """ValidateSubmitOrderRequestPositionAssets - a model defined in Swagger"""  # noqa: E501
        self._asset_id = None
        self._kind = None
        self._borrowed = None
        self._impending_borrows = None
        self._available = None
        self._locked = None
        self.discriminator = None
        self.asset_id = asset_id
        self.kind = kind
        self.borrowed = borrowed
        self.impending_borrows = impending_borrows
        self.available = available
        self.locked = locked

    @property
    def asset_id(self):
        """Gets the asset_id of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501


        :return: The asset_id of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this ValidateSubmitOrderRequestPositionAssets.


        :param asset_id: The asset_id of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :type: str
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")  # noqa: E501

        self._asset_id = asset_id

    @property
    def kind(self):
        """Gets the kind of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501


        :return: The kind of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :rtype: AssetKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ValidateSubmitOrderRequestPositionAssets.


        :param kind: The kind of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :type: AssetKind
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def borrowed(self):
        """Gets the borrowed of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501


        :return: The borrowed of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :rtype: str
        """
        return self._borrowed

    @borrowed.setter
    def borrowed(self, borrowed):
        """Sets the borrowed of this ValidateSubmitOrderRequestPositionAssets.


        :param borrowed: The borrowed of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :type: str
        """
        if borrowed is None:
            raise ValueError("Invalid value for `borrowed`, must not be `None`")  # noqa: E501

        self._borrowed = borrowed

    @property
    def impending_borrows(self):
        """Gets the impending_borrows of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501


        :return: The impending_borrows of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :rtype: str
        """
        return self._impending_borrows

    @impending_borrows.setter
    def impending_borrows(self, impending_borrows):
        """Sets the impending_borrows of this ValidateSubmitOrderRequestPositionAssets.


        :param impending_borrows: The impending_borrows of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :type: str
        """
        if impending_borrows is None:
            raise ValueError("Invalid value for `impending_borrows`, must not be `None`")  # noqa: E501

        self._impending_borrows = impending_borrows

    @property
    def available(self):
        """Gets the available of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501


        :return: The available of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :rtype: str
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this ValidateSubmitOrderRequestPositionAssets.


        :param available: The available of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :type: str
        """
        if available is None:
            raise ValueError("Invalid value for `available`, must not be `None`")  # noqa: E501

        self._available = available

    @property
    def locked(self):
        """Gets the locked of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501


        :return: The locked of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :rtype: str
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """Sets the locked of this ValidateSubmitOrderRequestPositionAssets.


        :param locked: The locked of this ValidateSubmitOrderRequestPositionAssets.  # noqa: E501
        :type: str
        """
        if locked is None:
            raise ValueError("Invalid value for `locked`, must not be `None`")  # noqa: E501

        self._locked = locked

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidateSubmitOrderRequestPositionAssets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidateSubmitOrderRequestPositionAssets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
