# coding: utf-8

"""
    DORA

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WithdrawalInitiation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'withdrawal_id': 'dict',
        'user_id': 'dict',
        'position_id': 'dict',
        'asset_id': 'dict',
        'quantity': 'dict',
        'status': 'WithdrawalStatus',
        'created_at': 'dict',
        'created_by': 'dict',
        'updated_at': 'dict',
        'updated_by': 'dict',
        'reason': 'dict'
    }

    attribute_map = {
        'withdrawal_id': 'withdrawal_id',
        'user_id': 'user_id',
        'position_id': 'position_id',
        'asset_id': 'asset_id',
        'quantity': 'quantity',
        'status': 'status',
        'created_at': 'created_at',
        'created_by': 'created_by',
        'updated_at': 'updated_at',
        'updated_by': 'updated_by',
        'reason': 'reason'
    }

    def __init__(self, withdrawal_id=None, user_id=None, position_id=None, asset_id=None, quantity=None, status=None, created_at=None, created_by=None, updated_at=None, updated_by=None, reason=None):  # noqa: E501
        """WithdrawalInitiation - a model defined in Swagger"""  # noqa: E501
        self._withdrawal_id = None
        self._user_id = None
        self._position_id = None
        self._asset_id = None
        self._quantity = None
        self._status = None
        self._created_at = None
        self._created_by = None
        self._updated_at = None
        self._updated_by = None
        self._reason = None
        self.discriminator = None
        self.withdrawal_id = withdrawal_id
        self.user_id = user_id
        self.position_id = position_id
        self.asset_id = asset_id
        self.quantity = quantity
        self.status = status
        self.created_at = created_at
        self.created_by = created_by
        self.updated_at = updated_at
        self.updated_by = updated_by
        self.reason = reason

    @property
    def withdrawal_id(self):
        """Gets the withdrawal_id of this WithdrawalInitiation.  # noqa: E501


        :return: The withdrawal_id of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._withdrawal_id

    @withdrawal_id.setter
    def withdrawal_id(self, withdrawal_id):
        """Sets the withdrawal_id of this WithdrawalInitiation.


        :param withdrawal_id: The withdrawal_id of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if withdrawal_id is None:
            raise ValueError("Invalid value for `withdrawal_id`, must not be `None`")  # noqa: E501

        self._withdrawal_id = withdrawal_id

    @property
    def user_id(self):
        """Gets the user_id of this WithdrawalInitiation.  # noqa: E501


        :return: The user_id of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this WithdrawalInitiation.


        :param user_id: The user_id of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def position_id(self):
        """Gets the position_id of this WithdrawalInitiation.  # noqa: E501


        :return: The position_id of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._position_id

    @position_id.setter
    def position_id(self, position_id):
        """Sets the position_id of this WithdrawalInitiation.


        :param position_id: The position_id of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if position_id is None:
            raise ValueError("Invalid value for `position_id`, must not be `None`")  # noqa: E501

        self._position_id = position_id

    @property
    def asset_id(self):
        """Gets the asset_id of this WithdrawalInitiation.  # noqa: E501


        :return: The asset_id of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this WithdrawalInitiation.


        :param asset_id: The asset_id of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if asset_id is None:
            raise ValueError("Invalid value for `asset_id`, must not be `None`")  # noqa: E501

        self._asset_id = asset_id

    @property
    def quantity(self):
        """Gets the quantity of this WithdrawalInitiation.  # noqa: E501


        :return: The quantity of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this WithdrawalInitiation.


        :param quantity: The quantity of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def status(self):
        """Gets the status of this WithdrawalInitiation.  # noqa: E501


        :return: The status of this WithdrawalInitiation.  # noqa: E501
        :rtype: WithdrawalStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this WithdrawalInitiation.


        :param status: The status of this WithdrawalInitiation.  # noqa: E501
        :type: WithdrawalStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def created_at(self):
        """Gets the created_at of this WithdrawalInitiation.  # noqa: E501


        :return: The created_at of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WithdrawalInitiation.


        :param created_at: The created_at of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this WithdrawalInitiation.  # noqa: E501


        :return: The created_by of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this WithdrawalInitiation.


        :param created_by: The created_by of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def updated_at(self):
        """Gets the updated_at of this WithdrawalInitiation.  # noqa: E501


        :return: The updated_at of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this WithdrawalInitiation.


        :param updated_at: The updated_at of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def updated_by(self):
        """Gets the updated_by of this WithdrawalInitiation.  # noqa: E501


        :return: The updated_by of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._updated_by

    @updated_by.setter
    def updated_by(self, updated_by):
        """Sets the updated_by of this WithdrawalInitiation.


        :param updated_by: The updated_by of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if updated_by is None:
            raise ValueError("Invalid value for `updated_by`, must not be `None`")  # noqa: E501

        self._updated_by = updated_by

    @property
    def reason(self):
        """Gets the reason of this WithdrawalInitiation.  # noqa: E501


        :return: The reason of this WithdrawalInitiation.  # noqa: E501
        :rtype: dict
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this WithdrawalInitiation.


        :param reason: The reason of this WithdrawalInitiation.  # noqa: E501
        :type: dict
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WithdrawalInitiation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WithdrawalInitiation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
